#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Part of the Earth & Beyond emulator preservation project -- Freya (MIT).
# License: LICENSES/Freya
#
# gen_loot.py -- ADDITIVE loot for the synthesized capture-import mob templates.
#
# The capture import (gen_sql.py) synthesizes a mob_base template (mob_id >=
# MOB_SYNTH_BASE) for every captured mob whose exact name is not already in
# mob_base. Those clone templates carry the right model + stats but NO loot:
# nothing copies mob_items onto them, so the synth mobs drop nothing when killed.
# This generator fills that gap, WITHOUT regenerating the import -- it layers a
# standalone, idempotent seed_capture_loot.sql on top that assigns loot to the
# synth templates only (mob_id >= MOB_SYNTH_BASE). It never touches base loot.
#
# Two tiers, most-authoritative first:
#
#   (b) RECONSTRUCT-BY-NAME. If the synth mob's name matches a mob in the
#       reconstruct dataset (ENB_RECONSTRUCT_DIR/db/mobs/mobs.jsonl) that lists
#       drop items, and those item names resolve to item_base rows, emit those
#       items as the loot table. Reconstruct rarely carries real per-item drop
#       rates (dropRatesAvailable is mostly false), so the items are given an
#       EVEN split summing to exactly 100 -- the server (HuskClass::PopulateHusk)
#       throttles over-tier / over-priced drops itself, so an even table is safe.
#
#   (a) SIBLING-TEMPLATE INHERITANCE (fallback). If no reconstruct match, copy
#       the loot of the nearest-level same-model (same base_asset_id) BASE mob
#       that actually has loot. This mirrors how gen_sql synthesizes the template
#       itself (clone the nearest-level same-asset mob), so the loot is at least
#       model- and level-appropriate. A synth mob whose model has no loot-bearing
#       sibling (e.g. a turret / test drone) gets no loot -- which is correct.
#
# Wire fidelity: mob_items.drop_chance is read as a float and stored (unsigned
# char) by the server, so tier-b uses INTEGER chances that sum to exactly 100
# (total_chance == 100 avoids the server's ">100%" loot warning). usage_chance
# and type are not consulted by the drop roll; tier-b uses 0/0 (the dominant base
# convention), qty 1.
#
# Source of the synth templates: the running net7 DB (mob_id >= MOB_SYNTH_BASE).
# If the DB has none (e.g. generating against a pristine base DB before the
# capture import is applied), the committed _mob_templates.sql is parsed instead,
# so this generator is independent of whether the import has been applied yet.
#
# Regenerate with import.sh (runs this after gen_sql/gen_turrets), or directly:
#   ENB_RECONSTRUCT_DIR=/path/to/reconstruct \
#     python3 .claude/skills/import-captures/scripts/gen_loot.py
# With ENB_RECONSTRUCT_DIR unset, tier (b) is skipped and every synth mob falls
# back to tier (a).
import collections
import json
import os
import re
import subprocess

PG_CONTAINER = os.environ.get("ENB_PG_CONTAINER", "freya-postgres-1")
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
OUT = os.path.join(REPO, "db", "postgres", "seed_capture_loot.sql")
TEMPLATES_SQL = os.path.join(REPO, "db", "postgres", "capture_import", "_mob_templates.sql")

# Reconstruct dataset root (external, gitignored). No default points anywhere
# real -- unset means tier (b) is skipped (tier-a only). Never hardcode a path.
RECON_DIR = os.environ.get("ENB_RECONSTRUCT_DIR", "").strip()

MOB_SYNTH_BASE = 900_000         # matches gen_sql.py: synthetic mob_base.mob_id floor
# mob_items.id is GENERATED BY DEFAULT AS IDENTITY. schema-init applies this file
# BEFORE sync_sequences.sql, so the identity sequence still sits at last_value=1
# on a fresh boot (base rows were bulk-loaded with EXPLICIT ids, which do not
# advance the sequence). Letting the id auto-allocate here would draw 1,2,3,... and
# collide with existing base rows. So, like every other synth insert in the import,
# emit an EXPLICIT id from a high synth-only band (base mob_items ids are < ~12000);
# sync_sequences.sql runs last and bumps the sequence past these.
LOOT_ID_BASE = 900_000           # synthetic mob_items.id floor (clear of base ids)


def pg(sql):
    out = subprocess.run(
        ["docker", "exec", PG_CONTAINER, "psql", "-U", "net7", "-d", "net7",
         "-tA", "-F", "\x1f", "-c", sql],
        capture_output=True, text=True, check=True).stdout
    return [line.split("\x1f") for line in out.splitlines() if line]


def sql_str(s):
    return "'" + str(s).replace("'", "''") + "'"


def norm(s):
    return re.sub(r"[^a-z0-9]", "", (s or "").lower())


def parse_values(tuple_text):
    """Split a single SQL VALUES(...) tuple into fields at top-level commas,
    respecting '..' single-quoted strings with '' escapes. Returns raw field
    strings (quotes stripped for quoted values)."""
    fields, buf, i, n, in_str = [], [], 0, len(tuple_text), False
    while i < n:
        c = tuple_text[i]
        if in_str:
            if c == "'":
                if i + 1 < n and tuple_text[i + 1] == "'":
                    buf.append("'"); i += 2; continue
                in_str = False; i += 1; continue
            buf.append(c); i += 1; continue
        if c == "'":
            in_str = True; i += 1; continue
        if c == ",":
            fields.append("".join(buf).strip()); buf = []; i += 1; continue
        buf.append(c); i += 1
    fields.append("".join(buf).strip())
    return fields


def synth_templates_from_file():
    """Fallback: parse (mob_id, name, level, base_asset_id) out of the committed
    _mob_templates.sql. Column order there is fixed:
    mob_id, name, level, intelligence, bravery, type, faction_id, base_asset_id, ..."""
    out = []
    rx = re.compile(r"VALUES\s*\((.*)\)\s*ON CONFLICT", re.IGNORECASE)
    with open(TEMPLATES_SQL) as fh:
        for line in fh:
            m = rx.search(line)
            if not m:
                continue
            f = parse_values(m.group(1))
            out.append((int(f[0]), f[1], int(f[2] or 0), int(f[7] or 0)))
    return out


def load_reconstruct():
    """normalized mob name -> [drop item names]. Empty if RECON_DIR unset/missing."""
    recon = {}
    if not RECON_DIR:
        return recon
    path = os.path.join(RECON_DIR, "db", "mobs", "mobs.jsonl")
    if not os.path.exists(path):
        print(f"gen_loot: WARNING reconstruct file not found: {path} -- tier (b) skipped")
        return recon
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            d = json.loads(line)
            nm = norm(d.get("name"))
            if not nm:
                continue
            items = [dr.get("item") for dr in (d.get("drops") or []) if dr.get("item")]
            if items:
                recon.setdefault(nm, [])
                for it in items:
                    if it not in recon[nm]:
                        recon[nm].append(it)
    return recon


def even_chances(n):
    """n integer drop chances summing to exactly 100 (front-loaded remainder)."""
    base = 100 // n
    rem = 100 - base * n
    return [base + (1 if i < rem else 0) for i in range(n)]


def normalize_over_100(loot):
    """A tier-a table copied from a base sibling can sum to >100 (a base-data
    quirk); the server then logs a 'Loot % above 100%' warning on every kill and
    scales by 100/total. Pre-scale such tables to sum EXACTLY 100 (integer,
    proportional) so drop behaviour is identical but no warning is emitted.
    Tables at/under 100 are returned unchanged -- their trash probability (roll >
    total -> trash) is intentional. loot: [(item_base_id, usage, drop, type, qty)]."""
    total = sum(r[2] for r in loot)
    if total <= 100.0:
        return loot
    scaled = [int(round(r[2] * 100.0 / total)) for r in loot]
    diff = 100 - sum(scaled)
    if diff:  # settle rounding drift on the highest-weight entry
        j = max(range(len(scaled)), key=lambda k: scaled[k])
        scaled[j] += diff
    return [(r[0], r[1], float(s), r[3], r[4]) for r, s in zip(loot, scaled)]


def main():
    # 1) synth templates (mob_id, name, level, asset). DB first, file fallback.
    synth = [(int(m), name, int(lvl or 0), int(asset or 0))
             for m, name, lvl, asset in pg(
                 "SELECT mob_id, name, level, base_asset_id FROM mob_base "
                 f"WHERE mob_id >= {MOB_SYNTH_BASE} ORDER BY mob_id")]
    src = "DB"
    if not synth:
        synth = sorted(synth_templates_from_file())
        src = os.path.relpath(TEMPLATES_SQL, REPO)
    if not synth:
        raise SystemExit("gen_loot: no synth templates in DB or _mob_templates.sql -- "
                         "run the capture import (gen_sql.py) first.")

    # 2) base mob loot, indexed by mob_id, plus each base mob's (level, asset).
    base_loot = collections.defaultdict(list)   # mob_id -> [(item_base_id, usage, drop, type, qty)]
    for mid, ib, uc, dc, ty, qt in pg(
            "SELECT mob_id, item_base_id, usage_chance, drop_chance, type, qty "
            f"FROM mob_items WHERE mob_id < {MOB_SYNTH_BASE} ORDER BY mob_id, id"):
        base_loot[int(mid)].append((int(ib), int(uc or 0), float(dc or 0), int(ty or 0), int(qt or 0)))

    # same-asset base mobs THAT HAVE loot, for sibling selection: asset -> [(mob_id, level)]
    loot_by_asset = collections.defaultdict(list)
    for mid, lvl, asset in pg(
            "SELECT mob_id, level, base_asset_id FROM mob_base "
            f"WHERE mob_id < {MOB_SYNTH_BASE} ORDER BY mob_id"):
        mid = int(mid)
        if mid in base_loot:
            loot_by_asset[int(asset or 0)].append((mid, int(lvl or 0)))

    # 3) item_base name -> id (lowest id wins on a normalized-name collision).
    name2id = {}
    for i, nm in pg("SELECT id, name FROM item_base WHERE name IS NOT NULL AND name <> ''"):
        k = norm(nm)
        if not k:
            continue
        i = int(i)
        if k not in name2id or i < name2id[k]:
            name2id[k] = i

    recon = load_reconstruct()

    # 4) assign loot per synth template.
    rows = []          # (mob_id, item_base_id, usage, drop, type, qty)
    n_b = n_a = n_none = 0
    none_names = []
    for mid, name, level, asset in synth:
        items = recon.get(norm(name))
        if items:
            ids, seen = [], set()
            for it in items:
                iid = name2id.get(norm(it))
                if iid is not None and iid not in seen:
                    seen.add(iid); ids.append(iid)
            if ids:
                ids.sort()
                for iid, dc in zip(ids, even_chances(len(ids))):
                    rows.append((mid, iid, 0, float(dc), 0, 1))
                n_b += 1
                continue
        # tier (a): nearest-level same-asset base mob that has loot.
        cands = loot_by_asset.get(asset)
        if cands:
            src_id = min(cands, key=lambda c: (abs(c[1] - level), c[0]))[0]
            for ib, uc, dc, ty, qt in normalize_over_100(base_loot[src_id]):
                rows.append((mid, ib, uc, dc, ty, qt))
            n_a += 1
            continue
        n_none += 1
        none_names.append(name)

    # 5) emit the additive, idempotent seed file.
    body = [
        "-- seed_capture_loot.sql -- GENERATED by .claude/skills/import-captures/scripts/gen_loot.py.",
        "-- ADDITIVE loot for the synthesized capture-import mob templates",
        f"-- (mob_id >= {MOB_SYNTH_BASE}), which the import creates without loot. Layered on",
        "-- top of seed_captures.sql; does NOT regenerate the import and NEVER touches",
        "-- base loot. Tier (b) reconstruct-by-name, tier (a) same-model sibling loot.",
        f"-- {len(synth)} synth templates: {n_b} by reconstruct, {n_a} by sibling, "
        f"{n_none} left loot-less (model has no loot-bearing sibling).",
        "-- Idempotent: deletes its own synth-range loot first, so a re-apply is a clean replace.",
        "BEGIN;",
        "",
        f"DELETE FROM mob_items WHERE mob_id >= {MOB_SYNTH_BASE};",
        "",
    ]
    for i, (mid, ib, uc, dc, ty, qt) in enumerate(rows):
        # Explicit synth id (see LOOT_ID_BASE) -- do NOT rely on the identity
        # sequence, which is not synced until after this file on a fresh boot.
        rid = LOOT_ID_BASE + i
        # drop_chance is real; integers print without a trailing .0 to match base data.
        dcv = int(dc) if float(dc).is_integer() else dc
        body.append(
            "INSERT INTO mob_items (id, mob_id, item_base_id, usage_chance, drop_chance, type, qty) "
            f"VALUES ({rid}, {mid}, {ib}, {uc}, {dcv}, {ty}, {qt});")
    body += ["", "COMMIT;", ""]
    with open(OUT, "w") as fh:
        fh.write("\n".join(body))

    print(f"gen_loot: {len(synth)} synth templates (from {src}) -> "
          f"{n_b} reconstruct, {n_a} sibling, {n_none} loot-less; "
          f"{len(rows)} mob_items rows -> {OUT}")
    if none_names:
        print("  loot-less (no loot-bearing same-model sibling): " + ", ".join(none_names))


if __name__ == "__main__":
    main()
