using System;
using System.Data;
using CommonTools.Database;

namespace MobEditorAvalonia.SQL
{
    public sealed class MobItemsSQL
    {
        DataTable _mobItems;

        public MobItemsSQL()
        {
            _mobItems = DB.Instance.executeQuery(
                "SELECT * FROM \"mob_items\";", null, null);
        }

        public DataTable getMobItemsTable() => _mobItems;

        public DataRow[] getRowsByID(int mobID)
            => _mobItems.WhereIntEquals("mob_id", mobID);

        public void deleteRecord(DataRow dr)
        {
            DB.Instance.executeCommand(
                "DELETE FROM \"mob_items\" WHERE \"mob_id\"=@mid AND \"item_base_id\"=@ibid;",
                new[] { "mid", "ibid" },
                new[] { dr["mob_id"].ToString(), dr["item_base_id"].ToString() });
            _mobItems.Rows.Remove(dr);
        }

        public void updateRecord(DataRow dr)
        {
            DB.Instance.executeCommand(
                "UPDATE \"mob_items\" SET \"drop_chance\"=@dc, \"usage_chance\"=@uc, \"qty\"=@q " +
                "WHERE \"mob_id\"=@mid AND \"item_base_id\"=@ibid;",
                new[] { "dc", "uc", "q", "mid", "ibid" },
                new[] {
                    dr["drop_chance"].ToString(),
                    dr["usage_chance"].ToString(),
                    dr["qty"].ToString(),
                    dr["mob_id"].ToString(),
                    dr["item_base_id"].ToString(),
                });
        }

        public void insertRecord(DataRow dr)
        {
            // "id" is GENERATED BY DEFAULT AS IDENTITY: omit it from the
            // column list and let Postgres allocate it, then read the new
            // value back via RETURNING (an INSERT...RETURNING through
            // executeQuery is recorded by the change tracker).
            var dt = DB.Instance.executeQuery(
                "INSERT INTO \"mob_items\" (\"mob_id\", \"drop_chance\", " +
                "\"usage_chance\", \"qty\", \"item_base_id\", \"type\") " +
                "VALUES (@mid, @dc, @uc, @q, @ibid, @t) RETURNING \"id\" AS id;",
                new[] { "mid", "dc", "uc", "q", "ibid", "t" },
                new[] {
                    dr["mob_id"].ToString(),
                    dr["drop_chance"].ToString(),
                    dr["usage_chance"].ToString(),
                    dr["qty"].ToString(),
                    dr["item_base_id"].ToString(),
                    dr["type"].ToString(),
                });

            dr["id"] = Convert.ToInt64(dt.Rows[0]["id"]);
        }
    }
}
