-- fields.sql -- GENERATED by tools/prospecting-import.
-- Resource FIELDS that docs/prospecting/prospect_fields.jsonl indicates
-- but the DB lacked (no field within 8000 units of the nav). One invisible
-- field container per distinct node level at the nav position; children
-- render from the restypes models and draw ore from base_ore_list.
BEGIN;
-- purge any prior prospecting-generated synthetic rows (clean re-apply)
DELETE FROM sector_objects_harvestable_restypes WHERE group_id >= 3000000;
DELETE FROM sector_objects_harvestable WHERE resource_id >= 3000000;
DELETE FROM sector_objects WHERE sector_object_id >= 3000000;

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000000, 0, 0.0, 0.0, 0.0, 38, 1.0, -31670.0, 97670.0, 50.0, 0.0, 0.0, 0.0, 0.0, 'Jyn Field L1', 0, 5000.0, 1075, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000000, 1, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000000, 3000000, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000001, 3000000, 1822);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000002, 3000000, 1828);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000003, 3000000, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000001, 0, 0.0, 0.0, 0.0, 38, 1.0, -34420.0, 117880.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Lono Field L1', 0, 5000.0, 1075, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000001, 1, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000100, 3000001, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000101, 3000001, 1822);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000102, 3000001, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000002, 0, 0.0, 0.0, 0.0, 38, 1.0, 30540.0, 70580.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Markham Field L1', 0, 5000.0, 1075, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000002, 1, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000200, 3000002, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000201, 3000002, 1822);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000202, 3000002, 1828);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000203, 3000002, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000003, 0, 0.0, 0.0, 0.0, 38, 1.0, 30250.0, 120790.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Trin Field L1', 0, 5000.0, 1075, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000003, 1, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000300, 3000003, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000301, 3000003, 1834);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000302, 3000003, 1828);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000004, 0, 0.0, 0.0, 0.0, 38, 1.0, 122206.0, 84655.5, 0.0, 0.0, 0.0, 0.0, 0.0, 'Derelict Mining Station (off Saturn Beltway 4-5) Field L2', 0, 5000.0, 1076, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000004, 2, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000400, 3000004, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000401, 3000004, 1822);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000402, 3000004, 1828);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000403, 3000004, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000005, 0, 0.0, 0.0, 0.0, 38, 1.0, -88692.1, -114772.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'InfinityCorp Beltway 5 Field L2', 0, 5000.0, 1076, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000005, 2, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000500, 3000005, 1834);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000006, 0, 0.0, 0.0, 0.0, 38, 1.0, 128267.0, 43466.6, -200.0, 0.0, 0.0, 0.0, 0.0, 'Hau Field L1', 0, 5000.0, 1925, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000006, 1, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000600, 3000006, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000007, 0, 0.0, 0.0, 0.0, 38, 1.0, 179330.0, 139150.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Kitara''s Gate/Nav P18 Field L3', 0, 5000.0, 1925, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000007, 3, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000700, 3000007, 1828);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000701, 3000007, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000008, 0, 0.0, 0.0, 0.0, 38, 1.0, 179330.0, 139150.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Nav P18 Field L1', 0, 5000.0, 1925, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000008, 1, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000800, 3000008, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000801, 3000008, 1822);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000802, 3000008, 1828);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000803, 3000008, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000009, 0, 0.0, 0.0, 0.0, 38, 1.0, 74133.4, -100533.0, -2000.0, 0.0, 0.0, 0.0, 0.0, 'Spinward Belt 1 Field L1', 0, 5000.0, 2210, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000009, 1, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000900, 3000009, 1822);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300000901, 3000009, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000010, 0, 0.0, 0.0, 0.0, 38, 1.0, 90133.4, -71733.4, -1000.0, 0.0, 0.0, 0.0, 0.0, 'Spinward Belt 2 Field L2', 0, 5000.0, 2210, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000010, 2, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001000, 3000010, 1822);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001001, 3000010, 1131);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001002, 3000010, 1828);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000011, 0, 0.0, 0.0, 0.0, 38, 1.0, 94400.1, -50400.1, 0.0, 0.0, 0.0, 0.0, 0.0, 'Spinward Belt 3 Field L1', 0, 5000.0, 2210, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000011, 1, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001100, 3000011, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001101, 3000011, 1828);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001102, 3000011, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000012, 0, 0.0, 0.0, 0.0, 38, 1.0, 36390.0, -97310.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Gate to Alpha Centauri (SE) Field L4', 0, 5000.0, 1750, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000012, 4, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001200, 3000012, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001201, 3000012, 1822);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001202, 3000012, 1828);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001203, 3000012, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000013, 0, 0.0, 0.0, 0.0, 38, 1.0, -202133.0, -90400.1, 0.0, 0.0, 0.0, 0.0, 0.0, 'Haster''s Point (south of sector) Field L7', 0, 5000.0, 4025, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000013, 7, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001300, 3000013, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001301, 3000013, 1822);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001302, 3000013, 1828);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001303, 3000013, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000014, 0, 0.0, 0.0, 0.0, 38, 1.0, -13780.0, 125030.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Arx Ymir (E) Field L2', 0, 5000.0, 1740, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000014, 2, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001400, 3000014, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001401, 3000014, 1822);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001402, 3000014, 1828);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001403, 3000014, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000015, 0, 0.0, 0.0, 0.0, 38, 1.0, -13780.0, 125030.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Arx Ymir (E) Field L3', 0, 5000.0, 1740, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000015, 3, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001500, 3000015, 1131);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000016, 0, 0.0, 0.0, 0.0, 38, 1.0, -13780.0, 125030.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Arx Ymir (E) Field L4', 0, 5000.0, 1740, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000016, 4, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001600, 3000016, 1131);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000017, 0, 0.0, 0.0, 0.0, 38, 1.0, -59700.0, 49040.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Lilo Field L3', 0, 5000.0, 1915, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000017, 3, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001700, 3000017, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000018, 0, 0.0, 0.0, 0.0, 38, 1.0, 35160.0, -59820.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Veil Trader Beacon Field L4', 0, 5000.0, 1915, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000018, 4, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001800, 3000018, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001801, 3000018, 1822);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001802, 3000018, 1131);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001803, 3000018, 1828);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001804, 3000018, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000019, 0, 0.0, 0.0, 0.0, 38, 1.0, 35160.0, -59820.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Veil Trader Beacon Field L5', 0, 5000.0, 1915, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000019, 5, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300001900, 3000019, 1131);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000020, 0, 0.0, 0.0, 0.0, 38, 1.0, 35160.0, -59820.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Veil Trader Beacon Field L7', 0, 5000.0, 1915, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000020, 7, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002000, 3000020, 1131);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000021, 0, 0.0, 0.0, 0.0, 38, 1.0, 176710.0, 400.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Sosti Alpha 3 Field L3', 0, 5000.0, 1725, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000021, 3, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002100, 3000021, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002101, 3000021, 1828);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002102, 3000021, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000022, 0, 0.0, 0.0, 0.0, 38, 1.0, 23320.0, 66120.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Gate to Muspelheim Field L3', 0, 5000.0, 1720, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000022, 3, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002200, 3000022, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002201, 3000022, 1822);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002202, 3000022, 1828);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002203, 3000022, 1825);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000023, 0, 0.0, 0.0, 0.0, 38, 1.0, 18850.8, 70724.0, 1238.83, 0.0, 0.0, 0.0, 0.0, 'Putotl Resource Point Field L2', 0, 5000.0, 4120, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000023, 2, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002300, 3000023, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002301, 3000023, 1834);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002302, 3000023, 1828);

INSERT INTO sector_objects (sector_object_id, base_asset_id, h, s, v, type, scale, position_x, position_y, position_z, orientation_u, orientation_v, orientation_w, orientation_z, name, appears_in_radar, radar_range, sector_id, gate_to, sound_effect_id, sound_effect_range) VALUES (3000024, 0, 0.0, 0.0, 0.0, 38, 1.0, 122850.0, 55430.0, -510.0, 0.0, 0.0, 0.0, 0.0, 'Climber''s Threat Field L2', 0, 5000.0, 3530, NULL, NULL, NULL);
INSERT INTO sector_objects_harvestable (resource_id, level, field, res_count, spawn_radius, pop_rock_chance, max_field_radius, respawn_timer) VALUES (3000024, 2, 0, 10, 0.0, 3.0, 8000.0, 10);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002400, 3000024, 1831);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002401, 3000024, 1822);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002402, 3000024, 1828);
INSERT INTO sector_objects_harvestable_restypes (id, group_id, type) VALUES (300002403, 3000024, 1825);

COMMIT;
