using System;
using System.Collections.Generic;
using Avalonia.Controls;
using Avalonia.Input;
using CommonTools.Database;
using MsBox.Avalonia;
using MsBox.Avalonia.Enums;
using MsBoxIcon = MsBox.Avalonia.Enums.Icon;

namespace CommonTools.Gui
{
    public partial class DlgSearchCriteria : Window
    {
        SearchCriteria m_searchCriteria = new SearchCriteria();

        public DlgSearchCriteria()
        {
            InitializeComponent();

            var comparisons = new List<string>
            {
                SearchCriteria.getComparatorSymbol(0) + "   (lesser than)",
                SearchCriteria.getComparatorSymbol(1) + "  (lesser or equal)",
                SearchCriteria.getComparatorSymbol(2) + "   (equal)",
                SearchCriteria.getComparatorSymbol(3) + "  (greater or equal)",
                SearchCriteria.getComparatorSymbol(4) + "   (greater than)",
            };
            guiComparisonCbo.ItemsSource = comparisons;
            guiComparisonCbo.SelectedIndex = 0;

            guiOkBtn.Click          += (_, _) => OnOk();
            guiCancelBtn.Click      += (_, _) => Close();
            guiPatternTipBtn.Click  += (_, _) => OnPatternTip();
            guiFieldCbo.SelectionChanged += (_, _) => OnFieldSelected();
            KeyDown += OnKeyDown;

            Opened += (_, _) => m_searchCriteria = new SearchCriteria();
        }

        // InitializeComponent generated by the Avalonia XAML compiler;
        // do not hand-roll one or it shadows the x:Name field wiring.

        public void configure(ColumnData.ColumnDataInfo[] fieldNames)
        {
            var items = new List<object>();
            foreach (var f in fieldNames) items.Add(f);
            guiFieldCbo.ItemsSource = items;
            if (items.Count != 0)
            {
                guiFieldCbo.SelectedIndex = 0;
                OnFieldSelected();
            }
        }

        public SearchCriteria getSearchCriteria() => m_searchCriteria;

        public void setSearchCriteria(SearchCriteria sc)
        {
            m_searchCriteria = sc;
            var items = guiFieldCbo.ItemsSource as IList<object>;
            if (items != null)
            {
                for (int i = 0; i < items.Count; i++)
                {
                    if (((ColumnData.ColumnDataInfo)items[i]).Name.Equals(m_searchCriteria.column))
                    {
                        guiFieldCbo.SelectedIndex = i;
                        break;
                    }
                }
            }
            OnFieldSelected();
        }

        void OnPatternTip()
        {
            MessageBoxManager.GetMessageBoxStandard("Pattern",
                "Use the % character to match against 'any'.\n"
              + "For example:\n"
              + "\tchavez%\t to find names beginning with 'chavez'\n"
              + "\t%chemical%\t to find names containing 'chemical'\n"
              + "\t%missile\t to find names ending with 'missile'.",
                ButtonEnum.Ok, MsBoxIcon.Info).ShowWindowDialogAsync(this);
        }

        void OnFieldSelected()
        {
            var col = guiFieldCbo.SelectedItem as ColumnData.ColumnDataInfo;
            if (col == null) return;
            bool isString = col.TypeIsString;

            guiPatternTxt.IsEnabled    = isString;
            guiPatternTxt.Text         = isString ? m_searchCriteria.criteria : "";
            guiPatternTipBtn.IsEnabled = isString;
            guiComparisonCbo.IsEnabled = !isString;
            if (guiComparisonCbo.IsEnabled)
            {
                guiComparisonCbo.SelectedIndex = m_searchCriteria.comparisonSymbol;
            }
            else
            {
                guiComparisonCbo.SelectedIndex = -1;
            }
            guiComparisonTxt.IsEnabled = guiComparisonCbo.IsEnabled;
            guiComparisonTxt.Text      = guiComparisonTxt.IsEnabled ? m_searchCriteria.criteria : "";
        }

        void OnOk()
        {
            var col = guiFieldCbo.SelectedItem as ColumnData.ColumnDataInfo;
            if (col == null) { Close(); return; }
            bool isString = col.TypeIsString;
            if (isString)
            {
                m_searchCriteria.comparisonSymbol = (string.IsNullOrEmpty(guiPatternTxt.Text)) ? 2 : 5;
                m_searchCriteria.criteria         = guiPatternTxt.Text ?? "";
                m_searchCriteria.subQuery         = col.Name + " " + m_searchCriteria.getComparatorSymbol()
                                                  + " " + DB.QueryParameterCharacter + col.Name;
                m_searchCriteria.sqlParameter     = col.Name;
                m_searchCriteria.sqlValue         = guiPatternTxt.Text ?? "";
            }
            else
            {
                if (string.IsNullOrEmpty(guiComparisonTxt.Text))
                {
                    MessageBoxManager.GetMessageBoxStandard("Search Criteria",
                        "You must enter a comparison value",
                        ButtonEnum.Ok, MsBoxIcon.Warning).ShowWindowDialogAsync(this);
                    guiComparisonTxt.Focus();
                    return;
                }
                m_searchCriteria.comparisonSymbol = guiComparisonCbo.SelectedIndex;
                m_searchCriteria.criteria         = guiComparisonTxt.Text;
                m_searchCriteria.subQuery         = col.Name + " " + m_searchCriteria.getComparatorSymbol()
                                                  + " " + DB.QueryParameterCharacter + col.Name;
                m_searchCriteria.sqlParameter     = col.Name;
                m_searchCriteria.sqlValue         = guiComparisonTxt.Text;
            }
            m_searchCriteria.column = col.Name;
            Close();
        }

        void OnKeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Return || e.Key == Key.Enter) OnOk();
            else if (e.Key == Key.Escape) Close();
        }
    }
}
