using System;
using System.Collections.Generic;
using System.Data;
using Avalonia.Collections;
using Avalonia.Controls;
using CommonTools.Database;

namespace CommonTools.Gui
{
    // Avalonia port of Gui/DlgSearch.cs. WinForms ListView replaced by
    // DataGrid (built-in sortable columns; no need for the WinForms
    // ListViewColumnSorter). Search criteria list stays as a ListBox.
    public partial class DlgSearch : Window
    {
        string m_selectedId = "";
        DlgSearchCriteria m_dlgSearchCriteria;
        Net7.Tables m_table;
        Enum[] m_columns;

        readonly AvaloniaList<SearchCriteria> m_criteria = new AvaloniaList<SearchCriteria>();
        readonly DataTable m_results = new DataTable();

        public DlgSearch()
        {
            InitializeComponent();
            guiResultLbl.Text = "";
            guiSearchCriteriaTbl.ItemsSource = m_criteria;

            guiAddBtn.Click    += async (_, _) => await OnAdd();
            guiEditBtn.Click   += async (_, _) => await OnEdit();
            guiRemoveBtn.Click += (_, _) => OnRemove();
            guiSearchBtn.Click += (_, _) => OnSearch();
            guiOkBtn.Click     += (_, _) => OnOk();
            guiCancelBtn.Click += (_, _) => Close();

            Opened += (_, _) => m_selectedId = "";
        }

        // InitializeComponent generated by the Avalonia XAML compiler;
        // do not hand-roll one or it shadows the x:Name field wiring.

        public string getSelectedId() => m_selectedId;

        async System.Threading.Tasks.Task OnAdd()
        {
            await m_dlgSearchCriteria.ShowDialog(this);
            var sc = m_dlgSearchCriteria.getSearchCriteria();
            if (!sc.IsEmpty())
            {
                m_criteria.Add(sc);
                guiSearchCriteriaTbl.SelectedIndex = m_criteria.Count - 1;
            }
        }

        async System.Threading.Tasks.Task OnEdit()
        {
            var sc = guiSearchCriteriaTbl.SelectedItem as SearchCriteria;
            if (sc == null) return;
            m_dlgSearchCriteria.setSearchCriteria(sc);
            await m_dlgSearchCriteria.ShowDialog(this);
            sc = m_dlgSearchCriteria.getSearchCriteria();
            if (!sc.IsEmpty())
            {
                int idx = guiSearchCriteriaTbl.SelectedIndex;
                m_criteria[idx] = sc;
            }
        }

        void OnRemove()
        {
            var sc = guiSearchCriteriaTbl.SelectedItem as SearchCriteria;
            if (sc == null) return;
            int idx = guiSearchCriteriaTbl.SelectedIndex;
            m_criteria.Remove(sc);
            if (idx >= m_criteria.Count) idx--;
            if (m_criteria.Count != 0) guiSearchCriteriaTbl.SelectedIndex = idx;
        }

        public void configure(Net7.Tables table)
        {
            if (!m_table.Equals(table))
            {
                m_criteria.Clear();
                m_results.Clear();
                guiResultTbl.ItemsSource = null;
                guiResultLbl.Text = "";
            }

            m_table = table;
            ColumnData.ColumnDataInfo[] fields = null;
            switch (m_table)
            {
                case Net7.Tables.effects:
                    m_columns = new Enum[] { Net7.Table_effects._effect_id, Net7.Table_effects._description, Net7.Table_effects._base_asset_id };
                    fields = Enumeration.ToColumnDataInfo<Net7.Table_effects>(true);
                    break;
                case Net7.Tables.factions:
                    m_columns = new Enum[] { Net7.Table_factions._faction_id, Net7.Table_factions._name };
                    fields = Enumeration.ToColumnDataInfo<Net7.Table_factions>(true);
                    break;
                case Net7.Tables.item_base:
                    m_columns = new Enum[] { Net7.Table_item_base._id, Net7.Table_item_base._name, Net7.Table_item_base._category,
                                              Net7.Table_item_base._sub_category, Net7.Table_item_base._level, Net7.Table_item_base._status };
                    fields = Enumeration.ToColumnDataInfo<Net7.Table_item_base>(true);
                    break;
                case Net7.Tables.missions:
                    m_columns = new Enum[] { Net7.Table_missions._mission_id, Net7.Table_missions._mission_name,
                                              Net7.Table_missions._mission_type, Net7.Table_missions._mission_key };
                    fields = Enumeration.ToColumnDataInfo<Net7.Table_missions>(true);
                    break;
                case Net7.Tables.mob_base:
                    m_columns = new Enum[] { Net7.Table_mob_base._mob_id, Net7.Table_mob_base._name };
                    fields = Enumeration.ToColumnDataInfo<Net7.Table_mob_base>(true);
                    break;
                case Net7.Tables.starbase_npcs:
                    m_columns = new Enum[] { Net7.Table_starbase_npcs._npc_Id, Net7.Table_starbase_npcs._first_name, Net7.Table_starbase_npcs._last_name };
                    fields = Enumeration.ToColumnDataInfo<Net7.Table_starbase_npcs>(true);
                    break;
                case Net7.Tables.sectors:
                    m_columns = new Enum[] { Net7.Table_sectors._sector_id, Net7.Table_sectors._name };
                    fields = Enumeration.ToColumnDataInfo<Net7.Table_sectors>(true);
                    break;
                case Net7.Tables.sector_objects:
                    m_columns = new Enum[] { Net7.Table_sector_objects._sector_object_id, Net7.Table_sector_objects._name,
                                              Net7.Table_sector_objects._base_asset_id, Net7.Table_sector_objects._sector_id };
                    fields = Enumeration.ToColumnDataInfo<Net7.Table_sector_objects>(true);
                    break;
                case Net7.Tables.skills:
                    m_columns = new Enum[] { Net7.Table_skills._skill_id, Net7.Table_skills._name };
                    fields = Enumeration.ToColumnDataInfo<Net7.Table_skills>(true);
                    break;
                default:
                    throw new Exception("DlgSearch.configure() does not handle the table " + table.ToString());
            }

            guiResultTbl.Columns.Clear();
            for (int i = 0; i < m_columns.Length; i++)
            {
                string colName = ColumnData.GetName(m_columns[i]);
                guiResultTbl.Columns.Add(new DataGridTextColumn
                {
                    Header  = colName,
                    Binding = new Avalonia.Data.Binding("[" + colName + "]"),
                    Width   = DataGridLength.SizeToCells,
                });
            }

            m_dlgSearchCriteria = new DlgSearchCriteria();
            m_dlgSearchCriteria.configure(fields);
        }

        void OnSearch()
        {
            string query = "";
            var sqlParameters = new List<string>();
            var sqlValues     = new List<string>();
            int parameterId = 0;

            foreach (SearchCriteria sc in m_criteria)
            {
                if (query.Length != 0) query += " AND ";
                query += sc.getQuery() + parameterId.ToString();
                sqlParameters.Add(sc.sqlParameter + parameterId.ToString());
                sqlValues.Add(sc.sqlValue);
                parameterId++;
            }

            if (query.Length == 0) return;

            string select = "";
            foreach (Enum col in m_columns)
            {
                if (select.Length == 0) select = DB.SELECT;
                else                    select += ",";
                select += ColumnData.GetName(col);
            }
            query = select + DB.FROM + m_table.ToString() + DB.WHERE + query;

            DataTable dt = DB.Instance.executeQuery(query, sqlParameters.ToArray(), sqlValues.ToArray());
            guiResultTbl.ItemsSource = dt.DefaultView;
            guiResultLbl.Text = dt.Rows.Count.ToString() + " items";
        }

        void OnOk()
        {
            var row = guiResultTbl.SelectedItem as DataRowView;
            if (row == null) return;
            m_selectedId = row[0].ToString();
            Close();
        }
    }
}
