using System;
using System.Data;
using System.IO;
using System.Xml;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Markup.Xaml;
using Npgsql;
using MsBox.Avalonia;
using MsBox.Avalonia.Enums;
using MsBoxIcon = MsBox.Avalonia.Enums.Icon;

namespace CommonTools.Gui
{
    // Avalonia port of Gui/Login.cs. Preserves the public API
    // (isValid()/updateVersion()/LoginData) so downstream tools can swap
    // CommonTools.dll for CommonToolsAvalonia.dll with no source change.
    public partial class Login : Window
    {
        bool m_Cancel = false;
        bool m_HasChanged;
        bool m_updateVersion = false;

        public Login()
        {
            InitializeComponent();
            // Route DB error MessageBoxes through our toolkit. Stays installed
            // even if Login is closed — host can override if they need to.
            // Marshal to the UI thread: DB calls run on worker threads now, and
            // the message box must be created/shown on the UI thread.
            Database.DBErrorReporter.Show = (title, body) =>
                Avalonia.Threading.Dispatcher.UIThread.Post(() =>
                    MessageBoxManager.GetMessageBoxStandard(title, body, ButtonEnum.Ok, MsBoxIcon.Error)
                                     .ShowWindowAsync());

            Opened += (_, _) =>
            {
                ReadConfiguration();
                DisplayConfiguration();
            };

            LoginButton.Click += async (_, _) => await AcceptedLoginInformation();
            ExitLogin.Click   += (_, _) => { m_Cancel = true; Close(); };

            foreach (var tb in new[] { LoginUsername, LoginPassword, SQLServer, SQLPort })
            {
                tb.TextChanged += (_, _) => m_HasChanged = true;
                tb.KeyDown     += OnTextBoxKey;
            }
        }

        // InitializeComponent is generated by Avalonia's XAML compiler from
        // the partial class + .axaml pair; do not provide a hand-rolled one
        // here (that would shadow the generated wiring of x:Name fields and
        // produce NREs when the constructor touches LoginUsername et al.).

        public bool isValid() => !m_Cancel;
        public void updateVersion() => m_updateVersion = true;

        async void OnTextBoxKey(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Enter || e.Key == Key.Return)
            {
                await AcceptedLoginInformation();
            }
        }

        static string ConfigPath() =>
            Path.Combine(AppContext.BaseDirectory, "Config.xml");

        void ReadConfiguration()
        {
            // Precedence: env vars (set by the `just` launcher for the local
            // stack) > Config.xml (a previously-saved manual entry) > the local
            // dev-stack defaults. The env path is what makes "launched via just
            // -> just click Login" work with zero typing.
            if (LoginData.LoadFromEnvironment()) return;

            try
            {
                DataSet ds = new DataSet();
                ds.ReadXml(ConfigPath());
                DataRow row = ds.Tables[0].Rows[0];
                LoginData.Host = row.ItemArray[0].ToString();
                LoginData.Port = Int32.Parse(row.ItemArray[1].ToString());
                LoginData.User = row.ItemArray[2].ToString();
                LoginData.Pass = row.ItemArray[3].ToString();
            }
            catch (Exception)
            {
                // Local dev stack (docker-compose): Postgres `net7` DB, exposed
                // on host port 5434 (-> container 5432), creds net7/net7.
                LoginData.Host = "localhost";
                LoginData.Port = 5434;
                LoginData.User = "net7";
                LoginData.Pass = "net7";
            }
        }

        void DisplayConfiguration()
        {
            LoginUsername.Text = LoginData.User;
            LoginPassword.Text = LoginData.Pass;
            SQLServer.Text     = LoginData.Host;
            SQLPort.Text       = LoginData.Port.ToString();
        }

        void WriteConfiguration()
        {
            LoginData.User = LoginUsername.Text;
            LoginData.Pass = LoginPassword.Text;
            LoginData.Host = SQLServer.Text;
            LoginData.Port = Convert.ToInt32(SQLPort.Text, 10);

            using var w = new XmlTextWriter(ConfigPath(), null);
            w.Formatting = Formatting.Indented;
            w.WriteStartDocument();
            w.WriteStartElement("Confg");
            w.WriteStartElement("Host"); w.WriteString(LoginData.Host); w.WriteEndElement();
            w.WriteStartElement("Port"); w.WriteString(LoginData.Port.ToString()); w.WriteEndElement();
            w.WriteStartElement("User"); w.WriteString(LoginData.User); w.WriteEndElement();
            w.WriteStartElement("Pass"); w.WriteString(LoginData.Pass); w.WriteEndElement();
            w.WriteEndElement();
            w.WriteEndDocument();
        }

        // Guards against re-entrancy (Enter held down / double-click) while a
        // login attempt is already running off-thread.
        bool m_loginInProgress;

        async System.Threading.Tasks.Task AcceptedLoginInformation()
        {
            if (m_loginInProgress) return;
            m_loginInProgress = true;
            m_Cancel = true;

            // Read UI on the UI thread, THEN do all blocking DB I/O on a worker
            // thread. The connect + version queries used to run synchronously
            // here on the UI thread: an unreachable/slow host froze the window
            // (and its X button) until the socket timed out. Keeping I/O off the
            // UI thread is what makes the window stay closable mid-login (AC.4).
            LoginData.User = LoginUsername.Text;
            LoginData.Pass = LoginPassword.Text;
            LoginData.Host = SQLServer.Text;
            try { LoginData.Port = Convert.ToInt32(SQLPort.Text, 10); }
            catch (Exception)
            {
                await ShowError("Invalid Port", "SQL Port must be a number.");
                m_loginInProgress = false;
                return;
            }

            var assemblyName = System.Reflection.Assembly.GetEntryAssembly()?.GetName();
            string connStr = LoginData.ConnStr(Database.DB.DATABASE_NAME);

            try
            {
                // result codes: 0 = ok, 1 = version updated (stop), 2 = outdated.
                // currentVersion is filled for the outdated message.
                string currentVersion = null;
                int outcome = await System.Threading.Tasks.Task.Run(() =>
                {
                    using (var conn = new NpgsqlConnection(connStr))
                    {
                        conn.Open();
                        conn.Close();
                    }

                    if (assemblyName == null) return 0; // library-only host: skip version check

                    if (m_updateVersion)
                    {
                        Database.DB.Instance.setVersion(assemblyName.Name, assemblyName.Version.ToString());
                        return 1;
                    }

                    currentVersion = Database.DB.Instance.getVersion(assemblyName.Name);
                    if (assemblyName.Version.ToString().CompareTo(currentVersion) != 0) return 2;
                    return 0;
                });

                if (outcome == 1)
                {
                    await ShowWarning("Version Updated",
                        "Database entry for " + assemblyName.Name + " has been updated to "
                        + LoginData.ApplicationVersion);
                    m_loginInProgress = false;
                    return;
                }
                if (outcome == 2)
                {
                    await ShowWarning("Incorrect Version",
                        assemblyName.Name + " " + LoginData.ApplicationVersion
                        + " is outdated.\nPlease update your editor to "
                        + LoginData.FormattedVersion(currentVersion));
                    m_loginInProgress = false;
                    return;
                }

                if (m_HasChanged) WriteConfiguration();
                m_Cancel = false;
                Close();
            }
            catch (Exception ex)
            {
                await ShowError("Connection Error", ex.Message + "\n" + ex.StackTrace);
                m_loginInProgress = false;
            }
        }

        System.Threading.Tasks.Task ShowError(string title, string body) =>
            MessageBoxManager.GetMessageBoxStandard(title, body, ButtonEnum.Ok, MsBoxIcon.Error)
                             .ShowWindowDialogAsync(this);

        System.Threading.Tasks.Task ShowWarning(string title, string body) =>
            MessageBoxManager.GetMessageBoxStandard(title, body, ButtonEnum.Ok, MsBoxIcon.Warning)
                             .ShowWindowDialogAsync(this);
    }

    public static class LoginData
    {
        static string m_Host;
        static int m_Port;
        static string m_User;
        static string m_Pass;
        static string m_ApplicationVersion;

        public static string Host { get => m_Host; set => m_Host = value; }
        public static int Port    { get => m_Port; set => m_Port = value; }
        public static string User { get => m_User; set => m_User = value; }
        public static string Pass { get => m_Pass; set => m_Pass = value; }

        public static string ConnStr(string DB)
        {
            // Short connect timeout so an unreachable host fails fast instead of
            // wedging the UI (Phase AC.4). Command Timeout bounds slow queries.
            return "Timeout=5"
                 + ";Command Timeout=30"
                 + ";Persist Security Info=False"
                 + ";Database=" + DB
                 + ";Host=" + m_Host
                 + ";Port=" + m_Port.ToString()
                 + ";Username=" + m_User
                 + ";Password=" + m_Pass;
        }

        /// <summary>
        /// Populate the login data from environment variables, if present. The
        /// `just` launcher sets these for the local docker stack so an editor
        /// launched that way needs no manual connection entry. Returns true when
        /// at least the host was provided (a complete-enough config to use).
        /// </summary>
        public static bool LoadFromEnvironment()
        {
            string host = Environment.GetEnvironmentVariable("ENB_DB_HOST");
            if (string.IsNullOrWhiteSpace(host)) return false;

            m_Host = host;
            string port = Environment.GetEnvironmentVariable("ENB_DB_PORT");
            m_Port = (!string.IsNullOrWhiteSpace(port) && int.TryParse(port, out int p)) ? p : 5434;
            m_User = Environment.GetEnvironmentVariable("ENB_DB_USER") ?? "net7";
            m_Pass = Environment.GetEnvironmentVariable("ENB_DB_PASS") ?? "net7";
            return true;
        }

        public static string ApplicationVersion
        {
            get
            {
                var an = System.Reflection.Assembly.GetEntryAssembly()?.GetName();
                if (an == null) return "v?.? Build ?.?";
                m_ApplicationVersion = FormattedVersion(an.Version.Major.ToString(),
                                                        an.Version.Minor.ToString(),
                                                        an.Version.Build.ToString(),
                                                        an.Version.Revision.ToString());
                return m_ApplicationVersion;
            }
        }

        public static string FormattedVersion(string version)
        {
            int majorVersion = version.IndexOf('.');
            int minorVersion = -1;
            int buildIndex = -1;
            int revisionIndex = -1;
            if (majorVersion == -1) { majorVersion = version.Length; }
            else
            {
                minorVersion = version.IndexOf('.', majorVersion + 1);
                if (minorVersion == -1) { minorVersion = version.Length; }
                else
                {
                    buildIndex = version.IndexOf('.', minorVersion + 1);
                    if (buildIndex == -1) { buildIndex = version.Length; }
                    else
                    {
                        revisionIndex = version.IndexOf('.', buildIndex + 1);
                        if (revisionIndex == -1) revisionIndex = version.Length;
                    }
                }
            }
            string major    = majorVersion == -1 ? "?" : version.Substring(0, majorVersion);
            string minor    = majorVersion == -1 || minorVersion == -1 ? "?" : version.Substring(majorVersion + 1, minorVersion - majorVersion - 1);
            string build    = minorVersion == -1 || buildIndex == -1 ? "?" : version.Substring(minorVersion + 1, buildIndex - minorVersion - 1);
            string revision = buildIndex == -1 || revisionIndex == -1 ? "?" : version.Substring(buildIndex + 1, revisionIndex - buildIndex - 1);
            return FormattedVersion(major, minor, build, revision);
        }

        public static string FormattedVersion(string major, string minor, string build, string revision)
        {
            return "v" + (major.Length == 0 ? "?" : major)
                 + "." + (minor.Length == 0 ? "?" : minor)
                 + " Build " + (build.Length == 0 ? "?" : build)
                 + "." + (revision.Length == 0 ? "?" : revision);
        }
    }
}
