using System;
using System.Data;
using System.IO;
using System.Xml;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Markup.Xaml;
using MySql.Data.MySqlClient;
using MsBox.Avalonia;
using MsBox.Avalonia.Enums;
using MsBoxIcon = MsBox.Avalonia.Enums.Icon;

namespace CommonTools.Gui
{
    // Avalonia port of Gui/Login.cs. Preserves the public API
    // (isValid()/updateVersion()/LoginData) so downstream tools can swap
    // CommonTools.dll for CommonToolsAvalonia.dll with no source change.
    public partial class Login : Window
    {
        bool m_Cancel = false;
        bool m_HasChanged;
        bool m_updateVersion = false;

        public Login()
        {
            InitializeComponent();
            // Route DB error MessageBoxes through our toolkit. Stays installed
            // even if Login is closed — host can override if they need to.
            Database.DBErrorReporter.Show = (title, body) =>
                MessageBoxManager.GetMessageBoxStandard(title, body, ButtonEnum.Ok, MsBoxIcon.Error)
                                 .ShowWindowAsync();

            Opened += (_, _) =>
            {
                ReadConfiguration();
                DisplayConfiguration();
            };

            LoginButton.Click += (_, _) => AcceptedLoginInformation();
            ExitLogin.Click   += (_, _) => { m_Cancel = true; Close(); };

            foreach (var tb in new[] { LoginUsername, LoginPassword, SQLServer, SQLPort })
            {
                tb.TextChanged += (_, _) => m_HasChanged = true;
                tb.KeyDown     += OnTextBoxKey;
            }
        }

        // InitializeComponent is generated by Avalonia's XAML compiler from
        // the partial class + .axaml pair; do not provide a hand-rolled one
        // here (that would shadow the generated wiring of x:Name fields and
        // produce NREs when the constructor touches LoginUsername et al.).

        public bool isValid() => !m_Cancel;
        public void updateVersion() => m_updateVersion = true;

        void OnTextBoxKey(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Enter || e.Key == Key.Return)
            {
                AcceptedLoginInformation();
            }
        }

        static string ConfigPath() =>
            Path.Combine(AppContext.BaseDirectory, "Config.xml");

        void ReadConfiguration()
        {
            try
            {
                DataSet ds = new DataSet();
                ds.ReadXml(ConfigPath());
                DataRow row = ds.Tables[0].Rows[0];
                LoginData.Host = row.ItemArray[0].ToString();
                LoginData.Port = Int32.Parse(row.ItemArray[1].ToString());
                LoginData.User = row.ItemArray[2].ToString();
                LoginData.Pass = row.ItemArray[3].ToString();
            }
            catch (Exception)
            {
                LoginData.Host = "net-7.org";
                LoginData.Port = 3307;
                LoginData.User = "";
                LoginData.Pass = "";
            }
        }

        void DisplayConfiguration()
        {
            LoginUsername.Text = LoginData.User;
            LoginPassword.Text = LoginData.Pass;
            SQLServer.Text     = LoginData.Host;
            SQLPort.Text       = LoginData.Port.ToString();
        }

        void WriteConfiguration()
        {
            LoginData.User = LoginUsername.Text;
            LoginData.Pass = LoginPassword.Text;
            LoginData.Host = SQLServer.Text;
            LoginData.Port = Convert.ToInt32(SQLPort.Text, 10);

            using var w = new XmlTextWriter(ConfigPath(), null);
            w.Formatting = Formatting.Indented;
            w.WriteStartDocument();
            w.WriteStartElement("Confg");
            w.WriteStartElement("Host"); w.WriteString(LoginData.Host); w.WriteEndElement();
            w.WriteStartElement("Port"); w.WriteString(LoginData.Port.ToString()); w.WriteEndElement();
            w.WriteStartElement("User"); w.WriteString(LoginData.User); w.WriteEndElement();
            w.WriteStartElement("Pass"); w.WriteString(LoginData.Pass); w.WriteEndElement();
            w.WriteEndElement();
            w.WriteEndDocument();
        }

        void AcceptedLoginInformation()
        {
            MySqlConnection conn = null;
            m_Cancel = true;
            try
            {
                LoginData.User = LoginUsername.Text;
                LoginData.Pass = LoginPassword.Text;
                LoginData.Host = SQLServer.Text;
                LoginData.Port = Convert.ToInt32(SQLPort.Text, 10);
                conn = new MySqlConnection(LoginData.ConnStr(Database.DB.DATABASE_NAME));
                conn.Open();
                conn.Close();

                var assemblyName = System.Reflection.Assembly.GetEntryAssembly()?.GetName();
                if (assemblyName == null)
                {
                    // Library-only host (no entry assembly) — skip version check.
                    if (m_HasChanged) WriteConfiguration();
                    m_Cancel = false;
                    Close();
                    return;
                }

                if (m_updateVersion)
                {
                    Database.DB.Instance.setVersion(assemblyName.Name, assemblyName.Version.ToString());
                    MessageBoxManager.GetMessageBoxStandard("Version Updated",
                        "Database entry for " + assemblyName.Name + " has been updated to "
                        + LoginData.ApplicationVersion,
                        ButtonEnum.Ok, MsBoxIcon.Warning).ShowWindowDialogAsync(this);
                    return;
                }

                string currentVersion = Database.DB.Instance.getVersion(assemblyName.Name);
                if (assemblyName.Version.ToString().CompareTo(currentVersion) != 0)
                {
                    MessageBoxManager.GetMessageBoxStandard("Incorrect Version",
                        assemblyName.Name + " " + LoginData.ApplicationVersion
                        + " is outdated.\nPlease update your editor to "
                        + LoginData.FormattedVersion(currentVersion),
                        ButtonEnum.Ok, MsBoxIcon.Warning).ShowWindowDialogAsync(this);
                    return;
                }

                if (m_HasChanged) WriteConfiguration();
                m_Cancel = false;
                Close();
            }
            catch (Exception ex)
            {
                MessageBoxManager.GetMessageBoxStandard(
                    "Connection Error",
                    ex.Message + "\n" + ex.StackTrace,
                    ButtonEnum.Ok, MsBoxIcon.Error).ShowWindowDialogAsync(this);
            }
            finally
            {
                if (conn != null) conn.Close();
            }
        }
    }

    public static class LoginData
    {
        static string m_Host;
        static int m_Port;
        static string m_User;
        static string m_Pass;
        static string m_ApplicationVersion;

        public static string Host { get => m_Host; set => m_Host = value; }
        public static int Port    { get => m_Port; set => m_Port = value; }
        public static string User { get => m_User; set => m_User = value; }
        public static string Pass { get => m_Pass; set => m_Pass = value; }

        public static string ConnStr(string DB)
        {
            return "Connect Timeout=30"
                 + ";Persist Security Info=False"
                 + ";Database=" + DB
                 + ";Host=" + m_Host
                 + ";Port=" + m_Port.ToString()
                 + ";Username=" + m_User
                 + ";Password=" + m_Pass;
        }

        public static string ApplicationVersion
        {
            get
            {
                var an = System.Reflection.Assembly.GetEntryAssembly()?.GetName();
                if (an == null) return "v?.? Build ?.?";
                m_ApplicationVersion = FormattedVersion(an.Version.Major.ToString(),
                                                        an.Version.Minor.ToString(),
                                                        an.Version.Build.ToString(),
                                                        an.Version.Revision.ToString());
                return m_ApplicationVersion;
            }
        }

        public static string FormattedVersion(string version)
        {
            int majorVersion = version.IndexOf('.');
            int minorVersion = -1;
            int buildIndex = -1;
            int revisionIndex = -1;
            if (majorVersion == -1) { majorVersion = version.Length; }
            else
            {
                minorVersion = version.IndexOf('.', majorVersion + 1);
                if (minorVersion == -1) { minorVersion = version.Length; }
                else
                {
                    buildIndex = version.IndexOf('.', minorVersion + 1);
                    if (buildIndex == -1) { buildIndex = version.Length; }
                    else
                    {
                        revisionIndex = version.IndexOf('.', buildIndex + 1);
                        if (revisionIndex == -1) revisionIndex = version.Length;
                    }
                }
            }
            string major    = majorVersion == -1 ? "?" : version.Substring(0, majorVersion);
            string minor    = majorVersion == -1 || minorVersion == -1 ? "?" : version.Substring(majorVersion + 1, minorVersion - majorVersion - 1);
            string build    = minorVersion == -1 || buildIndex == -1 ? "?" : version.Substring(minorVersion + 1, buildIndex - minorVersion - 1);
            string revision = buildIndex == -1 || revisionIndex == -1 ? "?" : version.Substring(buildIndex + 1, revisionIndex - buildIndex - 1);
            return FormattedVersion(major, minor, build, revision);
        }

        public static string FormattedVersion(string major, string minor, string build, string revision)
        {
            return "v" + (major.Length == 0 ? "?" : major)
                 + "." + (minor.Length == 0 ? "?" : minor)
                 + " Build " + (build.Length == 0 ? "?" : build)
                 + "." + (revision.Length == 0 ? "?" : revision);
        }
    }
}
