-- autocalib.lua -- guided runtime calibration for enb.self() (Phase AS-3).
--
-- The struct offsets in game.h default to "unknown", so enb.self() returns
-- { base = 0 } until you find the player-object pointer and field offsets for
-- THIS client build. They are install-specific, so they are not committed:
-- this helper finds them at runtime and writes scripts/calib_data.lua (gitignored),
-- which init.lua loads on the next start / hot-reload.
--
-- USAGE (in-game, with the chat HUD visible so you can read your real stats):
--   local ac = require("autocalib")
--   ac.find(1000)        -- pass your CURRENT hull value; scans .data for the
--                        -- pointer whose object holds that number. Prints
--                        -- candidate player_ptr_addr lines to enbmod.log.
--   ac.probe(0xADDR)     -- hex-dump the candidate object; eyeball which +0x..
--                        -- offsets hold hull/shield/energy/levels (match the HUD).
--   ac.save{             -- once you know them, persist + apply:
--       player_ptr_addr = 0x00B6xxxx,
--       hull = 0x.., hull_max = 0x.., shield = 0x.., shield_max = 0x..,
--       energy = 0x.., energy_max = 0x.., ... }
--
-- save() both calls enb.calibrate{...} (live now) AND writes calib_data.lua so
-- it survives a restart. There is no fully-automatic path: the field-offset
-- identification needs a human matching dumped values against the on-screen HUD.

local calib = require("calib")

local M = {}

-- Scan .data for the pointer leading to an object whose +probe_off dword equals
-- `hull_now`. probe_off defaults to 0 (try a few if the first guess misses).
function M.find(hull_now, probe_off, lo, hi)
    enb.log(("autocalib: scanning for hull=%d (probe_off=0x%x)"):format(
        hull_now, probe_off or 0))
    calib.find_ptr_to_value(hull_now, probe_off or 0, lo, hi)
end

-- Hex-dump a candidate object so you can read off field offsets.
function M.probe(base, count)
    calib.dump(base, count or 64)
end

-- The fields autocalib knows how to persist (mirror of game.h Offsets).
local FIELDS = {
    "player_ptr_addr",
    "hull", "hull_max", "shield", "shield_max", "energy", "energy_max",
    "combat_lvl", "trade_lvl", "explore_lvl",
    "combat_pct", "trade_pct", "explore_pct", "skill_points",
    "pos_x", "pos_y", "pos_z",
    "target_ptr_addr", "tgt_name", "tgt_name_is_ptr", "tgt_name_wide",
    "tgt_hull", "tgt_pos_x", "tgt_pos_y", "tgt_pos_z",
}

local function calib_data_path()
    -- package.path points at <mod>\scripts\?.lua; derive the dir from it.
    local p = package.path:match("([^;]*)\\scripts\\%?%.lua") or "."
    return p .. "\\scripts\\calib_data.lua"
end

-- Apply offsets live (enb.calibrate) and persist them to calib_data.lua.
function M.save(t)
    enb.calibrate(t)
    local path = calib_data_path()
    local f, err = io.open(path, "w")
    if not f then
        enb.log("autocalib: cannot write " .. path .. ": " .. tostring(err))
        return false
    end
    f:write("-- calib_data.lua -- generated by autocalib.save(). Gitignored.\n")
    f:write("-- Install-specific offsets for enb.self(); loaded by init.lua.\n")
    f:write("return {\n")
    for _, k in ipairs(FIELDS) do
        if t[k] ~= nil then
            f:write(("    %s = 0x%X,\n"):format(k, t[k]))
        end
    end
    f:write("}\n")
    f:close()
    enb.log("autocalib: wrote " .. path)
    return true
end

return M
