// SPDX-License-Identifier: CC-BY-NC-SA-3.0
// Part of the Earth & Beyond emulator preservation project.
// License: LICENSES/enb-emulator
//
// === AUTO-GENERATED — DO NOT EDIT BY HAND ===
// Source: common/include/net7/Opcodes.h
// Regenerate via: tools/cli-client/scripts/generate-opcode-names.sh

using System.Collections.Frozen;

namespace N7.CliClient.Opcodes;

/// <summary>
/// Human-readable names for every opcode declared in
/// <c>common/include/net7/Opcodes.h</c>. Generated from the C header
/// so the C# side stays in lockstep without manual transcription.
///
/// Used by the packet log to print "0x0033 CLIENT_CHAT" instead of
/// "0x0033 UNKNOWN", and by <c>OpcodeRegistry.RegisterAllOpaque</c>
/// to seed the registry with name-tagged opaque codecs for every
/// known opcode (Phase S Item 15).
/// </summary>
public static class OpcodeNames
{
    /// <summary>How many distinct opcodes the EnB protocol declares.</summary>
    public const int Count = 207;

    /// <summary>Maps opcode value → upstream symbolic name (e.g. CLIENT_CHAT).</summary>
    public static readonly FrozenDictionary<ushort, string> All =
        new Dictionary<ushort, string>
        {
            { 0x0000, "VERSION_REQUEST" },
            { 0x0001, "VERSION_RESPONSE" },
            { 0x0002, "LOGIN" },
            { 0x0003, "LOGOFF" },
            { 0x0004, "CREATE" },
            { 0x0005, "START" },
            { 0x0006, "START_ACK" },
            { 0x0007, "REMOVE" },
            { 0x0008, "SIMPLE_POSITIONAL_UDPATE" },
            { 0x0009, "OBJECT_EFFECT" },
            { 0x000A, "POINT_EFFECT" },
            { 0x000B, "OBJECT_TO_OBJECT_EFFECT" },
            { 0x000E, "OBJECT_TO_OBJECT_LINKED_EFFECT" },
            { 0x000F, "REMOVE_EFFECT" },
            { 0x0010, "DECAL" },
            { 0x0011, "COLORIZATION" },
            { 0x0012, "TURN" },
            { 0x0013, "TILT" },
            { 0x0014, "MOVE" },
            { 0x0017, "REQUEST_TARGET" },
            { 0x0018, "REQUEST_TARGETS_TARGET" },
            { 0x0019, "SET_TARGET" },
            { 0x001A, "DEBUG" },
            { 0x001B, "AUX_DATA" },
            { 0x001C, "PLAYER_VAR_AUX_DATA" },
            { 0x001D, "MESSAGE_STRING" },
            { 0x001E, "GROUP" },
            { 0x001F, "TRADE" },
            { 0x0020, "PRIORITY_MESSAGE" },
            { 0x0022, "PUSH_MESSAGE" },
            { 0x0025, "ITEM_BASE" },
            { 0x0026, "CHANGE_BASE_ASSET" },
            { 0x0027, "INVENTORY_MOVE" },
            { 0x0028, "INVENTORY_SORT" },
            { 0x0029, "ITEM_STATE" },
            { 0x002A, "SET_ZBAND" },
            { 0x002B, "SET_BBOX" },
            { 0x002C, "ACTION" },
            { 0x002D, "ACTION2" },
            { 0x002E, "OPTION" },
            { 0x002F, "INIT_RENDER_STATE" },
            { 0x0030, "ACTIVATE_RENDER_STATE" },
            { 0x0031, "ACTIVATE_NEXT_RENDER_STATE" },
            { 0x0032, "DEACTIVATE_RENDER_STATE" },
            { 0x0033, "CLIENT_CHAT" },
            { 0x0034, "CLIENT_SET_TIME" },
            { 0x0035, "MASTER_JOIN" },
            { 0x0036, "SERVER_REDIRECT" },
            { 0x0037, "CLIENT_AVATAR" },
            { 0x003A, "SERVER_HANDOFF" },
            { 0x003C, "CLIENT_TYPE" },
            { 0x003E, "ADVANCED_POSITIONAL_UPDATE" },
            { 0x003F, "PLANET_POSITIONAL_UPDATE" },
            { 0x0040, "CONSTANT_POSITIONAL_UPDATE" },
            { 0x0041, "FORMATION_POSITIONAL_UPDATE" },
            { 0x0042, "SERVER_PARAMETERS" },
            { 0x0043, "REQUEST_TRANSFORM_CHANGE" },
            { 0x0044, "REQUEST_TIME" },
            { 0x0046, "COMPONENT_POSITIONAL_UPDATE" },
            { 0x0047, "CLIENT_SHIP" },
            { 0x004A, "CREATE_ATTACHMENT" },
            { 0x004E, "STARBASE_REQUEST" },
            { 0x004F, "STARBASE_SET" },
            { 0x0051, "SKILL_STRING_RQ" },
            { 0x0052, "LOUNGE_NPC" },
            { 0x0053, "FIND_MEMBER" },
            { 0x0054, "TALK_TREE" },
            { 0x0055, "SELECT_TALK_TREE" },
            { 0x0056, "TALK_TREE_ACTION" },
            { 0x0057, "SKILL_UP" },
            { 0x0058, "SKILL_ABILITY" },
            { 0x005A, "VERB_REQUEST" },
            { 0x005C, "VERB_UPDATE" },
            { 0x005D, "EQUIP_USE" },
            { 0x005E, "AVATAR_EMOTE" },
            { 0x005F, "AVATAR_EMOTE_RESPONSE" },
            { 0x0061, "AVATAR_DESCRIPTION" },
            { 0x0064, "CLIENT_DAMAGE" },
            { 0x0065, "UI_TRIGGER" },
            { 0x0066, "OPEN_INTERFACE" },
            { 0x006A, "CLIENT_SOUND" },
            { 0x006D, "GLOBAL_CONNECT" },
            { 0x006E, "GLOBAL_TICKET_REQUEST" },
            { 0x006F, "GLOBAL_TICKET" },
            { 0x0070, "GLOBAL_AVATAR_LIST" },
            { 0x0071, "GLOBAL_DELETE_CHARACTER" },
            { 0x0072, "GLOBAL_CREATE_CHARACTER" },
            { 0x0075, "GLOBAL_ERROR" },
            { 0x0079, "MANUFACTURE_ITEM_CATAGORY" },
            { 0x007A, "MANUFACTURE_ITEM_CATAGORY" },
            { 0x007B, "MANUFACTURE_ITEM_ID" },
            { 0x007C, "REFINERY_ITEM_ID" },
            { 0x007E, "MANUFACTURE_ACTION" },
            { 0x007F, "MANUFACTURE_SET_MANUFACTURE_ID" },
            { 0x0080, "MANUFACTURE_TECH_LEVEL_FILTER" },
            { 0x0081, "RECUSTOMIZE_SHIP_START" },
            { 0x0082, "RECUSTOMIZE_SHIP_DONE" },
            { 0x0083, "RECUSTOMIZE_AVATAR_START" },
            { 0x0084, "RECUSTOMIZE_AVATAR_DONE" },
            { 0x0085, "RECUSTOMIZE_AVATAR_UPDATE" },
            { 0x0086, "MISSION_FORFEIT" },
            { 0x0087, "MISSION_DISMISSAL" },
            { 0x0088, "PETITION_STUCK" },
            { 0x0089, "RELATIONSHIP" },
            { 0x008B, "ATTACKER_UPDATES" },
            { 0x008C, "LOOT_HULK_PERMISSION" },
            { 0x008D, "INCAPACITANCE_REQUEST" },
            { 0x0092, "CAMERA_CONTROL" },
            { 0x0093, "JOB_LIST" },
            { 0x0094, "JOB_DESCRIPTION" },
            { 0x0095, "JOB_DELETE" },
            { 0x0096, "JOB_ACCEPT_REPLY" },
            { 0x0097, "GALAXY_MAP" },
            { 0x0098, "GALAXY_MAP_REQUEST" },
            { 0x0099, "NAVIGATION" },
            { 0x009B, "WARP" },
            { 0x009C, "WARP_INDEX" },
            { 0x009D, "STARBASE_AVATAR_CHANGE" },
            { 0x009E, "STARBASE_AVATAR_CHANGE" },
            { 0x009F, "STARBASE_ROOM_CHANGE" },
            { 0x00A0, "STARBASE_ROOM_CHANGE" },
            { 0x00A1, "TRIGGER_EMOTE" },
            { 0x00A2, "NOTIFY_EMOTE" },
            { 0x00A3, "CLIENT_CHAT_REQUEST" },
            { 0x00A4, "CLIENT_CHAT_LIST" },
            { 0x00A5, "CLIENT_CHAT_EVENT" },
            { 0x00A6, "CLIENT_CHAT_ERROR" },
            { 0x00B2, "NAME_DECAL" },
            { 0x00B4, "SUBPARTS" },
            { 0x00B9, "LOGOFF_REQUEST" },
            { 0x00BA, "LOGOFF_CONFIRMATION" },
            { 0x00BC, "CTA_REQUEST" },
            { 0x00BD, "CTA_RESPONSE" },
            { 0x00BE, "CONFIRMED_ACTION_OFFER" },
            { 0x00C0, "CONFIRMED_ACTION_RESPONSE" },
            { 0x00C5, "GUILD_LEADER_ACCEPT_CLIENT" },
            { 0x00C8, "GUILD_RECRUIT_CONFIRM_SECTOR" },
            { 0x00C9, "GUILD_RECRUIT_ACCEPT_CLIENT" },
            { 0x00CC, "GUILD_SIMPLE_SECTOR_CLIENT" },
            { 0x00CD, "GUILD_SIMPLE_CLIENT_SECTOR" },
            { 0x00D0, "GUILD_MESSAGE_SECTOR" },
            { 0x00D2, "GUILD_PLAYER_PERMISSIONS" },
            { 0x00D3, "GUILD_RANK_NAMES_SECTOR" },
            { 0x00D4, "GUILD_RANK_NAMES_REQUEST_CLIENT" },
            { 0x00D5, "GUILD_RANK_NAMES_GUILD" },
            { 0x00DD, "GPS_REQUEST" },
            { 0x1000, "MVAS_REGISTER_C_S" },
            { 0x1001, "MVAS_LOGIN_S_C" },
            { 0x1004, "MVAS_SEND_POSITION_C_S" },
            { 0x1006, "MVAS_RESET_POSITION_S_C" },
            { 0x1007, "MVAS_TOGGLE_SEND_FREQ_S_C" },
            { 0x1008, "MVAS_LOGOFF_C_S" },
            { 0x1009, "MVAS_BAD_LOGIN_S_C" },
            { 0x100A, "MVAS_TERMINATE_S_C" },
            { 0x100B, "MVAS_PRE_START_S_C" },
            { 0x2000, "ACCOUNTDATA" },
            { 0x2001, "ACCOUNTVALID" },
            { 0x2002, "TICKET" },
            { 0x2003, "AVATARLIST" },
            { 0x2004, "AVATARLOGIN" },
            { 0x2005, "AVATARLOGIN_CONFIRM" },
            { 0x2006, "SECTOR_VALIDATE" },
            { 0x2007, "SECTOR_VALID_CONFIRM" },
            { 0x2008, "MASTER_HANDOFF" },
            { 0x2009, "MASTER_HANDOFF_CONFIRM" },
            { 0x200A, "CLIENT_OPCODE" },
            { 0x200B, "CREATE_AVATAR" },
            { 0x200C, "CREATE_DELETE_AVATAR_CONFIRM" },
            { 0x200D, "DELETE_AVATAR" },
            { 0x200E, "GLOBAL_ERROR" },
            { 0x200F, "COMM_PORT" },
            { 0x2010, "SET_GLOBAL_LOGIN_LINK_OR_DATA_FILE" },
            { 0x2011, "SET_PROXY_SECTOR_LINK_OR_GALAXY_MAP_CACHE" },
            { 0x2012, "START_PROSPECT" },
            { 0x2013, "TRACTOR_ORE" },
            { 0x2014, "LOOT_ITEM" },
            { 0x2015, "STARBASE_AVATAR" },
            { 0x2016, "PACKET_SEQUENCE" },
            { 0x2017, "RESEND_PACKET_SEQUENCE" },
            { 0x2018, "STATIC_OBJECT_CREATE" },
            { 0x2019, "RESOURCE_OBJECT_CREATE" },
            { 0x201A, "PACKET_C_SEQUENCE" },
            { 0x2020, "LOGIN_STAGE_S_C" },
            { 0x2021, "LOGIN_STAGE_ACK_C_S" },
            { 0x3000, "WAIT_AUX" },
            { 0x3001, "AUX_RESPONSE" },
            { 0x3002, "TCP_LOGIN_VALIDATE" },
            { 0x3003, "TCP_LOGIN_CLOSE" },
            { 0x3004, "PLAYER_SHIP_SENT" },
            { 0x3005, "PLAYER_COMMS_ALIVE" },
            { 0x3006, "PLAYER_LOGIN_FAILED" },
            { 0x3007, "PLAYER_LOGIN_FAILED_CONFIRM" },
            { 0x3008, "STARBASE_LOGIN_COMPLETE" },
            { 0x4000, "SSL_REGISTER_SSL_S" },
            { 0x4001, "SSL_REGISTER_S_SSL" },
            { 0x4002, "SSL_PLAYERCOUNT" },
            { 0x4003, "SSL_AVATARLOGIN_SSL_S" },
            { 0x4004, "SSL_AVATARCONFIRM_S_SSL" },
            { 0x5000, "GET_PLAYER_COUNT" },
            { 0x5001, "RETURN_PLAYER_COUNT" },
            { 0x7801, "SECTOR_ASSIGNMENT" },
            { 0x7802, "REQUEST_CHARACTER_DATA" },
            { 0x7803, "SECTOR_SHUTDOWN" },
            { 0x7804, "CHAT_MESSAGE" },
            { 0x7805, "WHERE_IS_PLAYER" },
            { 0x7902, "CHARACTER_DATA" },
            { 0x7905, "PLAYER_LOCATION" },
        }.ToFrozenDictionary();

    /// <summary>
    /// Look up an opcode's symbolic name. Returns "0xNNNN UNKNOWN" for
    /// opcodes outside Opcodes.h. Never throws.
    /// </summary>
    public static string Get(OpcodeId opcode) =>
        All.TryGetValue(opcode.Value, out var name) ? name : "UNKNOWN";

    /// <summary>
    /// Render in the form "0xNNNN NAME" suitable for log lines.
    /// </summary>
    public static string Format(OpcodeId opcode) =>
        $"{opcode} {Get(opcode)}";
}
