using System;
using Avalonia.Controls;
using Avalonia.Input;

namespace CommonTools.Gui
{
    public partial class DlgEditXml : Window
    {
        bool m_madeSelection;
        string m_xml;

        public DlgEditXml()
        {
            InitializeComponent();
            m_xml = "";

            guiOkBtn.Click     += (_, _) => { m_madeSelection = true; m_xml = guiXmlTxt.Text; Close(); };
            guiCancelBtn.Click += (_, _) => Close();
            KeyDown            += OnKeyDown;

            Opened += (_, _) =>
            {
                m_madeSelection = false;
                guiXmlTxt.Focus();
                guiXmlTxt.SelectionStart = 0;
                guiXmlTxt.SelectionEnd   = 0;
                guiXmlTxt.TextChanged += OnTextChanged;
            };
        }

        // InitializeComponent generated by the Avalonia XAML compiler;
        // do not hand-roll one or it shadows the x:Name field wiring.

        public void setXml(string xml)
        {
            m_xml = xml;
            guiXmlTxt.Text = m_xml;
        }

        public bool getValues(out string xml)
        {
            xml = m_xml;
            return m_madeSelection;
        }

        void OnTextChanged(object sender, EventArgs e)
        {
            guiOkBtn.IsEnabled = true;
            guiXmlTxt.TextChanged -= OnTextChanged;
        }

        void OnKeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyModifiers.HasFlag(KeyModifiers.Control) && e.Key == Key.A)
            {
                guiXmlTxt.SelectAll();
            }
        }
    }
}
