-- _mob_templates.sql -- GENERATED by .claude/skills/import-captures.
-- Synthetic mob_base templates for captured mobs whose exact name is
-- not in mob_base. Each is a clone of the nearest-level same-asset
-- template carrying the captured name/level/asset, so the captured mob
-- spawns with the right model + valid stats. Included FIRST so the
-- per-sector spawns can reference them.
BEGIN;
DELETE FROM mob_base WHERE mob_id >= 900000;
INSERT INTO mob_base (mob_id, name, level, intelligence, bravery, type, faction_id, base_asset_id, altruism, aggressiveness, ai, h, s, v, scale, skill0, skill1, skill2, skill3, skill4, skill5, skill6, skill7, skill8, skill9, skillchance, skillcooldown, shield_modifier, damage_modifier, range_modifier) VALUES (900000, 'Starbase Guardian Turret', 66, 0, 0, 1, 6, 14, 0, 0, '[10/02/2009: Marco removed whiteling at Webbys request

Added gate defense beam at 100 usage. 

Also adjusted level to 66 from 50 so the turret can actualy use level 9 beams

Altered faction back to EarthCorps Warriors so now Yellow to all players]', 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 1, 1, 1) ON CONFLICT (mob_id) DO NOTHING;
INSERT INTO mob_base (mob_id, name, level, intelligence, bravery, type, faction_id, base_asset_id, altruism, aggressiveness, ai, h, s, v, scale, skill0, skill1, skill2, skill3, skill4, skill5, skill6, skill7, skill8, skill9, skillchance, skillcooldown, shield_modifier, damage_modifier, range_modifier) VALUES (900001, 'Craxel', 7, 0, 0, 2, 0, 398, 0, 3, '', 0, 0, 0, 0.5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 1, 1, 1) ON CONFLICT (mob_id) DO NOTHING;
INSERT INTO mob_base (mob_id, name, level, intelligence, bravery, type, faction_id, base_asset_id, altruism, aggressiveness, ai, h, s, v, scale, skill0, skill1, skill2, skill3, skill4, skill5, skill6, skill7, skill8, skill9, skillchance, skillcooldown, shield_modifier, damage_modifier, range_modifier) VALUES (900002, 'Resource Hound', 12, 0, 0, 1, 0, 426, 0, 5, '[Byakhee Jul 2009]
[Skeletor 12/09/09]
[Added L3 Beam Saint Jacques Iku: Dropchance 2]
[Added L3 Reactor Honour: Dropchance 5]
[Added L4 Device Radiant Warp Kaza: Dropchance 1]
[Added L3 Device Musca II RS 3: Dropchance 5]
[Added L4 Black Market Waepons Crates: Dropchance 1]
[Added L3 Computer Core: Dropchance 10]
[Added L3 Used Warp Stabilizer: Dropchance 10]
[Added L2 Destroyed Weapon: Dropchance 15]
[Added L2 Power Coupling: Dropchance 20]
', 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 1, 1, 1) ON CONFLICT (mob_id) DO NOTHING;
INSERT INTO mob_base (mob_id, name, level, intelligence, bravery, type, faction_id, base_asset_id, altruism, aggressiveness, ai, h, s, v, scale, skill0, skill1, skill2, skill3, skill4, skill5, skill6, skill7, skill8, skill9, skillchance, skillcooldown, shield_modifier, damage_modifier, range_modifier) VALUES (900003, 'Resource Hound', 11, 0, 0, 1, 0, 426, 0, 5, '[Byakhee Jul 2009]
[Skeletor 12/09/09]
[Added L3 Beam Saint Jacques Iku: Dropchance 2]
[Added L3 Reactor Honour: Dropchance 5]
[Added L4 Device Radiant Warp Kaza: Dropchance 1]
[Added L3 Device Musca II RS 3: Dropchance 5]
[Added L4 Black Market Waepons Crates: Dropchance 1]
[Added L3 Computer Core: Dropchance 10]
[Added L3 Used Warp Stabilizer: Dropchance 10]
[Added L2 Destroyed Weapon: Dropchance 15]
[Added L2 Power Coupling: Dropchance 20]
', 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 1, 1, 1) ON CONFLICT (mob_id) DO NOTHING;
INSERT INTO mob_base (mob_id, name, level, intelligence, bravery, type, faction_id, base_asset_id, altruism, aggressiveness, ai, h, s, v, scale, skill0, skill1, skill2, skill3, skill4, skill5, skill6, skill7, skill8, skill9, skillchance, skillcooldown, shield_modifier, damage_modifier, range_modifier) VALUES (900004, 'Resource Hunter', 7, 0, 0, 1, 0, 425, 0, 5, '[Byakhee:  07/03/2009]
[Co:  Cyclo Power Exch]
[Mc:  Terminal Overide v7.0]
[De:  Steingards Embrace, Thordis Lament, C Australis PR 6, Targe VI,  RoadRunner V]
[Wep: Sleeping Lion,  Growling Mastiff, Haralds Berserk, Skofung, Thorgils Fury, Whitting]
[Sh: Great Dane VIII,  More Adorable Class 3 Shield]
[Re:  Nova Mk VII]', 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 1, 1, 1) ON CONFLICT (mob_id) DO NOTHING;
INSERT INTO mob_base (mob_id, name, level, intelligence, bravery, type, faction_id, base_asset_id, altruism, aggressiveness, ai, h, s, v, scale, skill0, skill1, skill2, skill3, skill4, skill5, skill6, skill7, skill8, skill9, skillchance, skillcooldown, shield_modifier, damage_modifier, range_modifier) VALUES (900005, 'Resource Hunter', 5, 0, 0, 1, 0, 425, 0, 5, '[Byakhee:  07/03/2009]
[Co:  Cyclo Power Exch]
[Mc:  Terminal Overide v7.0]
[De:  Steingards Embrace, Thordis Lament, C Australis PR 6, Targe VI,  RoadRunner V]
[Wep: Sleeping Lion,  Growling Mastiff, Haralds Berserk, Skofung, Thorgils Fury, Whitting]
[Sh: Great Dane VIII,  More Adorable Class 3 Shield]
[Re:  Nova Mk VII]', 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 1, 1, 1) ON CONFLICT (mob_id) DO NOTHING;
INSERT INTO mob_base (mob_id, name, level, intelligence, bravery, type, faction_id, base_asset_id, altruism, aggressiveness, ai, h, s, v, scale, skill0, skill1, skill2, skill3, skill4, skill5, skill6, skill7, skill8, skill9, skillchance, skillcooldown, shield_modifier, damage_modifier, range_modifier) VALUES (900006, 'The Wrangler', 16, 0, 0, 1, 0, 425, 0, 5, '[Byakhee:  07/03/2009]
[Co:  Cyclo Power Exch]
[Mc:  Terminal Overide v7.0]
[De:  Steingards Embrace, Thordis Lament, C Australis PR 6, Targe VI,  RoadRunner V]
[Wep: Sleeping Lion,  Growling Mastiff, Haralds Berserk, Skofung, Thorgils Fury, Whitting]
[Sh: Great Dane VIII,  More Adorable Class 3 Shield]
[Re:  Nova Mk VII]', 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 1, 1, 1) ON CONFLICT (mob_id) DO NOTHING;
INSERT INTO mob_base (mob_id, name, level, intelligence, bravery, type, faction_id, base_asset_id, altruism, aggressiveness, ai, h, s, v, scale, skill0, skill1, skill2, skill3, skill4, skill5, skill6, skill7, skill8, skill9, skillchance, skillcooldown, shield_modifier, damage_modifier, range_modifier) VALUES (900007, 'Rahu the Cultivator', 47, 0, 0, 1, 0, 1537, 0, 5, '', 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 1, 1, 1) ON CONFLICT (mob_id) DO NOTHING;
INSERT INTO mob_base (mob_id, name, level, intelligence, bravery, type, faction_id, base_asset_id, altruism, aggressiveness, ai, h, s, v, scale, skill0, skill1, skill2, skill3, skill4, skill5, skill6, skill7, skill8, skill9, skillchance, skillcooldown, shield_modifier, damage_modifier, range_modifier) VALUES (900008, 'Hadean Hijacker', 37, 0, 0, 1, 0, 426, 0, 5, '[Byakhee:  07/03/2009]
[Co:  Cyclo Power Exch]
[Mc:  Terminal Overide v7.0]
[De:  Cats paw L6, Steingards Embrace, Thordis Lament, C Australis PR 6, Targe VI,  RoadRunner V]
[Wep: Sleeping Lion,  Growling Mastiff, Haralds Berserk, Skofung, Thorgils Fury, Whitting]
[Sh: Great Dane VIII,  More Adorable Class 3 Shield]
[Re:  Nova Mk VII]', 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 1, 1, 1) ON CONFLICT (mob_id) DO NOTHING;
INSERT INTO mob_base (mob_id, name, level, intelligence, bravery, type, faction_id, base_asset_id, altruism, aggressiveness, ai, h, s, v, scale, skill0, skill1, skill2, skill3, skill4, skill5, skill6, skill7, skill8, skill9, skillchance, skillcooldown, shield_modifier, damage_modifier, range_modifier) VALUES (900009, 'Bardon Nesrith', 23, 0, 0, 1, 0, 434, 0, 0, '[Byakhee:  21/02/2009]
[Comp: Nova Engine Vault Pro]
[Weap:  Sleeping Great Dane]', 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 1, 1, 1) ON CONFLICT (mob_id) DO NOTHING;
COMMIT;
