-- _purge.sql -- GENERATED by .claude/skills/import-captures.
-- Remove ALL prior capture-import synthetic rows so a full re-apply over
-- a different prior id mapping is a clean replace, not a silent drop.
-- Runs FIRST (before _mob_templates.sql and the per-sector files).
-- Children before parents; keyed directly on the synthetic id range.
BEGIN;
DELETE FROM mob_spawn_group WHERE spawn_group_id >= 1000000;
DELETE FROM sector_objects_mob WHERE mob_id >= 1000000;
DELETE FROM sector_objects_harvestable_restypes WHERE group_id >= 1000000;
DELETE FROM sector_objects_harvestable_oretypes WHERE resource_id >= 1000000;
DELETE FROM sector_objects_harvestable WHERE resource_id >= 1000000;
DELETE FROM sector_nav_points WHERE sector_object_id >= 1000000;
DELETE FROM sector_objects WHERE sector_object_id >= 1000000;
COMMIT;
