using System;
using System.Data;
using CommonTools.Database;

namespace FactionEditor.SQL
{
    // Avalonia port of tools/faction-editor/SQL/FactionsSQL.cs. The
    // single change from the original is that we go through
    // commontools's DB.Instance (MySql.Data wrapped with
    // parameterised executeQuery/executeCommand) instead of the
    // per-tool Database wrapper, AND we replace the string-concat SQL
    // with parameterised placeholders — which closes the obvious
    // SQL-injection holes the original had on every name/description
    // field.
    public sealed class FactionsSQL
    {
        DataTable _factions;

        public FactionsSQL()
        {
            _factions = DB.Instance.executeQuery(
                "SELECT * FROM factions ORDER BY name;", null, null);
        }

        public DataTable getFactionTable() => _factions;

        public DataRow getRowByID(int id)
        {
            var rows = _factions.WhereIntEquals("faction_id", id);
            return rows.Length > 0 ? rows[0] : null;
        }

        public DataRow newRecord()
        {
            // faction_id is GENERATED BY DEFAULT AS IDENTITY -- omit it from
            // the INSERT and read it back with RETURNING (no LAST_INSERT_ID()
            // in Postgres). INSERT...RETURNING via executeQuery is recorded by
            // the change tracker.
            var lastInsert = DB.Instance.executeQuery(
                "INSERT INTO factions (\"name\", \"description\") VALUES (@name, @desc) RETURNING \"faction_id\" AS id;",
                new[] { "name", "desc" },
                new[] { "<New Faction>", "" });
            int lastInsertID = Convert.ToInt32(lastInsert.Rows[0]["id"]);

            var newRow = _factions.NewRow();
            newRow["faction_id"] = lastInsertID;
            newRow["name"]       = "<New Faction>";
            newRow["description"] = "";
            newRow["PDA_text"]    = "";
            _factions.Rows.Add(newRow);
            newRow.AcceptChanges();
            _factions.AcceptChanges();
            return newRow;
        }

        public void deleteRecord(int id, DataRow dr)
        {
            DB.Instance.executeCommand(
                "DELETE FROM factions WHERE \"faction_id\"=@id;",
                new[] { "id" },
                new[] { id.ToString() });
            _factions.Rows.Remove(dr);
        }

        public void updateRecord(DataRow dr)
        {
            int factionID = Convert.ToInt32(dr["faction_id"]);
            DB.Instance.executeCommand(
                "UPDATE factions SET \"name\"=@name, \"description\"=@desc, \"PDA_text\"=@pda WHERE \"faction_id\"=@id;",
                new[] { "name", "desc", "pda", "id" },
                new[] {
                    dr["name"].ToString(),
                    dr["description"].ToString(),
                    dr["PDA_text"].ToString(),
                    factionID.ToString(),
                });
        }
    }
}
