// SPDX-License-Identifier: MIT
// Part of the Earth & Beyond emulator preservation project -- Freya (MIT).
// License: LICENSES/Freya

using System.Runtime.CompilerServices;
using Npgsql;

namespace N7.CliClient.IntegrationTests;

/// <summary>
/// A test account that exists in the postgres net7_user.accounts table
/// for the lifetime of the test run.
/// </summary>
public sealed record TestAccount(int Id, string Username, string Password);

/// <summary>
/// On-demand test account provisioning.
///
/// <para>
/// Each call to <see cref="New"/> inserts a fresh row into the
/// net7_user.accounts table with a process-unique username and a
/// process-unique ID. No pre-seeded account pool; no per-test method
/// name mapping in source; no Fixtures/seed.sql.
/// </para>
///
/// <para>
/// Username shape: <c>t_&lt;8-hex&gt;_&lt;6-hex&gt;</c> where the first
/// 8 hex digits come from <see cref="ProcessUid"/> (one per test run)
/// and the last 6 come from <see cref="_counter"/> (monotonic, atomic).
/// Width = 17 chars, well under the accounts.username varchar(40)
/// limit. The per-process prefix prevents collisions if two test
/// runs accidentally share a database. The per-account counter
/// suffix makes IDs unique inside one run.
/// </para>
///
/// <para>
/// The accounts.id column is <c>GENERATED BY DEFAULT AS IDENTITY</c>
/// so we let postgres assign and read it back via <c>RETURNING id</c>.
/// The IDENTITY sequence is shared across runs, so two invocations
/// of the test suite against the same database produce strictly
/// increasing IDs (no collisions on re-run without volume wipe).
/// </para>
///
/// <para>
/// status defaults to 100 (ACTIVE/admin) which slash-command pinning
/// suites need so the GM (50) / DEV (80) / SDEV (90) inline gates open.
/// status flows through `AccountManager::HandleAvatarCreate` at
/// `server/src/AccountManager.cpp:1273` into `m_Database.info.admin_level`,
/// and `Player::AdminLevel()` at `server/src/PlayerClass.h:212` returns
/// it verbatim (the htonl/ntohl pair is a no-op on x86). At first sector
/// login `Player::FirstLogin` at `server/src/PlayerClass.cpp:397-407`
/// emits a 0x001D chat-tier banner gated on AdminLevel(): &gt;=DEV(80)
/// "Dev Chat..." / &gt;=GM(50) "GM Chat..." / &gt;=BETA(30) "Beta Chat...".
/// Tests that diff opcode histograms against a retail-player capture
/// (DockHandshakeFriendship7Tests) MUST pass <c>status:
/// <see cref="PlayerTierStatus"/></c> so the banner does NOT fire.
/// </para>
///
/// <para>
/// Other status values: 0 = STRESS_TEST_CLOSED (rejected with G_ERROR
/// 12 at server/src/UDP_Global.cpp:139), -1 = inactive registration
/// (rejected with G_ERROR 9), -2 = banned (rejected with G_ERROR 0).
/// </para>
/// </summary>
public static class TestAccounts
{
    public const string SharedPassword = "testpw";

    /// <summary>
    /// Sub-BETA(30) status value for tests that need a non-admin avatar
    /// (e.g. histogram parity vs a retail-player capture). The actual
    /// numeric value is arbitrary as long as it's positive (so the
    /// UDP_Global STRESS_TEST_CLOSED/INACTIVE/BANNED gates pass) and
    /// below BETA=30 (so no chat-tier banner fires from FirstLogin).
    /// 1 is the smallest such value.
    /// </summary>
    public const int PlayerTierStatus = 1;

    // Phase X: Argon2id PHC string for SharedPassword ("testpw"), produced
    // with libsodium's INTERACTIVE profile (m=64MiB, t=2, p=1). Stored as
    // a constant so the test suite doesn't need to pull a C# Argon2
    // implementation -- the server verifies via crypto_pwhash_str_verify,
    // which accepts any conforming Argon2id PHC regardless of the
    // implementation that produced it. If SharedPassword changes, this
    // string must be regenerated (see plans/24-phase-x-password-hash-modernization.md).
    private const string SharedPasswordPhc =
        "$argon2id$v=19$m=65536,t=2,p=1$yJ6EvyLVw7FE954o5j2knA$WbzKh+x/BRJdTBcaMBhR3Wo5JhbcYJIzierKkVOrFzE";

    // 8 hex digits drawn once per test process. The whole point is to
    // keep usernames stable across one run (so retries / log scraping
    // work) while preventing collisions across runs that race on the
    // same database -- e.g. a developer running tests locally while
    // CI runs them on a shared dev postgres.
    private static readonly string ProcessUid =
        Guid.NewGuid().ToString("N").Substring(0, 8);

    // Monotonic per-account counter. Interlocked.Increment is safe for
    // xUnit's parallel class execution.
    private static int _counter;

    /// <summary>
    /// Provision a fresh test account. Inserts a row into
    /// net7_user.accounts and returns the credentials.
    /// </summary>
    /// <param name="server">
    /// The collection fixture; used for its postgres connection string.
    /// </param>
    /// <param name="status">
    /// accounts.status: 100 = ACTIVE/admin (default; opens GM/DEV/SDEV
    /// gates for slash-command suites and fires the DEV chat-tier banner
    /// at FirstLogin). Pass <see cref="PlayerTierStatus"/> for a
    /// non-admin avatar that bypasses the chat-tier banner. 0 =
    /// STRESS_TEST_CLOSED (rejected). See class xmldoc for full table.
    /// </param>
    /// <param name="testName">
    /// Bound automatically via CallerMemberName. Used only for the
    /// formname column so a stray DB dump is grep-able back to the
    /// test that produced it; does not affect uniqueness.
    /// </param>
    public static TestAccount New(
        ServerFixture server,
        int status = 100,
        [CallerMemberName] string testName = "")
    {
        var slot = Interlocked.Increment(ref _counter);
        var username = $"t_{ProcessUid}_{slot:x6}";

        // Truncate formname to varchar(40). Test method names are
        // long ("StarbaseJobTerminalAction7_InNet7SolJtSector_..."),
        // so cap aggressively and prepend a short id chunk so dumps
        // can tie back even when the test name is clipped.
        var formname = (testName.Length > 32
            ? testName.Substring(0, 32)
            : testName);
        if (string.IsNullOrEmpty(formname)) formname = "unknown_test";

        using var conn = new NpgsqlConnection(server.PostgresConnectionString);
        conn.Open();
        using var cmd = new NpgsqlCommand(@"
            INSERT INTO accounts (username, password_phc, status, formname, email, warn_level)
            VALUES (@username, @password_phc, @status, @formname, @email, 0)
            RETURNING id",
            conn);
        cmd.Parameters.AddWithValue("username", username);
        cmd.Parameters.AddWithValue("password_phc", SharedPasswordPhc);
        cmd.Parameters.AddWithValue("status", status);
        cmd.Parameters.AddWithValue("formname", formname);
        cmd.Parameters.AddWithValue("email", $"{username}@net-7.test");
        var id = (int)(long)cmd.ExecuteScalar()!;

        return new TestAccount(id, username, SharedPassword);
    }
}
