#!/usr/bin/env bash
# db/postgres/convert.sh
#
# Convert the MySQL dumps in db/mysql/ to Postgres-flavoured SQL in
# db/postgres/.
#
# This is a sed pipeline. It is NOT a real translator. It catches the
# 80% mechanical-rename cases (backticks, ENGINE=..., AUTO_INCREMENT,
# tinyint/int-with-display-width, datetime, KEY ... inline indexes,
# FOREIGN_KEY_CHECKS, simple DROP TABLE statements). The residual ~20%
# (text vs varchar semantics, \0 NULs in INSERTs, MySQL escape strings,
# hex literals, comment-syntax oddities) is documented in
# db/postgres/README.md and will be cleaned up in Phase C.
#
# Usage: bash db/postgres/convert.sh
# Idempotent: re-running overwrites schema.sql / seed.sql.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC_DIR="${ROOT}/db/mysql"
DST_DIR="${ROOT}/db/postgres"

mkdir -p "${DST_DIR}"

convert() {
    local in="$1"
    local out="$2"
    if [[ ! -f "${in}" ]]; then
        echo "convert.sh: input missing: ${in}" >&2
        return 1
    fi

    # The pipeline below is deliberately a single `sed` invocation. Each
    # rule is annotated so future maintainers know what's intentional and
    # what's a hack.
    #
    # ORDERING NOTE: the prefixed-int rules (bigint/mediumint/smallint/tinyint)
    # MUST run BEFORE the plain `int(N)` rule. sed regex has no word boundary
    # in ERE, so a plain `int\(([0-9]+)\)` happily matches the `int(N)` tail
    # of `bigint(20)` and would produce nonsense like `biginteger`. Convert
    # the prefixed forms first so the trailing `(N)` is gone before plain-int
    # processing.
    sed -E \
        -e 's/SET FOREIGN_KEY_CHECKS=0;//g' \
        -e 's/SET FOREIGN_KEY_CHECKS=1;//g' \
        -e 's/`([^`]+)`/"\1"/g' \
        -e 's/\) ENGINE=[A-Za-z]+( DEFAULT CHARSET=[A-Za-z0-9_]+)?( COLLATE[ =][A-Za-z0-9_]+)?/)/g' \
        -e 's/DEFAULT CHARSET=[A-Za-z0-9_]+//g' \
        -e 's/COLLATE[ =][A-Za-z0-9_]+//g' \
        -e 's/bigint\(([0-9]+)\) unsigned/numeric(20,0)/g' \
        -e 's/bigint\(([0-9]+)\)/bigint/g' \
        -e 's/mediumint\(([0-9]+)\) unsigned/integer/g' \
        -e 's/mediumint\(([0-9]+)\)/integer/g' \
        -e 's/tinyint\(([0-9]+)\) unsigned/smallint/g' \
        -e 's/tinyint\(([0-9]+)\)/smallint/g' \
        -e 's/smallint\(([0-9]+)\) unsigned/integer/g' \
        -e 's/smallint\(([0-9]+)\)/smallint/g' \
        -e 's/int\(([0-9]+)\) unsigned/bigint/g' \
        -e 's/int\(([0-9]+)\)/integer/g' \
        -e 's/double\(([0-9]+),([0-9]+)\)/double precision/g' \
        -e 's/double unsigned/double precision/g' \
        -e 's/float\(([0-9]+),([0-9]+)\)/real/g' \
        -e 's/datetime/timestamp/g' \
        -e 's/AUTO_INCREMENT[= ]*[0-9]+//g' \
        -e 's/AUTO_INCREMENT/GENERATED BY DEFAULT AS IDENTITY/g' \
        -e 's/DROP TABLE IF EXISTS "([^"]+)"/DROP TABLE IF EXISTS "\1" CASCADE/g' \
        -e 's/^\s*KEY "([^"]+)" \(([^)]+)\),?$/  -- INDEX TODO: \1 ON (\2)/g' \
        -e 's/^\s*UNIQUE KEY "([^"]+)" \(([^)]+)\),?$/  -- UNIQUE INDEX TODO: \1 ON (\2)/g' \
        -e 's/^\s*FULLTEXT KEY "([^"]+)" \(([^)]+)\),?$/  -- FULLTEXT INDEX TODO: \1 ON (\2)/g' \
        -e 's/ COMMENT '"'"'[^'"'"']*'"'"'//g' \
        -e 's/\)[[:space:]]*COMMENT[[:space:]]*=[[:space:]]*'"'"'[^'"'"']*'"'"';/);/g' \
        -e 's/ CHARACTER SET [A-Za-z0-9_]+//g' \
        -e 's/(real|float|double precision|integer|bigint|smallint|numeric\([0-9,]+\))[[:space:]]+unsigned/\1/g' \
        -e 's/[[:space:]]+zerofill//g' \
        -e 's/USING BTREE//g' \
        -e 's/binary\(([0-9]+)\)/bytea/g' \
        -e 's/varbinary\(([0-9]+)\)/bytea/g' \
        -e 's/varchar\(0\)/text/g' \
        -e "s/'0000-00-00 00:00:00'/'1970-01-01 00:00:00'/g" \
        -e "s/'0000-00-00'/'1970-01-01'/g" \
        -e 's/^\s*KEY "([^"]+)" \(([^)]+)\)[[:space:]]*,?[[:space:]]*$/  -- INDEX TODO: \1 ON (\2)/g' \
        -e 's/^\s*CONSTRAINT "[^"]+" FOREIGN KEY[^,]*,$/  -- FK TODO/g' \
        -e 's/^\s*CONSTRAINT "[^"]+" FOREIGN KEY[^,]*$/  -- FK TODO/g' \
        "${in}" > "${out}"

    # MySQL allows bare `double` as a column type; Postgres needs
    # `double precision`. The earlier `double(N,N)` / `double unsigned`
    # sed rules already produce `double precision`, so we must only rewrite
    # bare `double` — and ONLY on lines that look like a CREATE TABLE
    # column definition (`  "col_name" double ...`). Anchoring on the
    # `<ws>"<ident>" double<ws>` shape avoids rewriting the word "double"
    # inside INSERT string-literal text ("double-crossing", "double the
    # other", etc.). The DDL convention used by mysqldump puts each column
    # on its own line, so this is reliable for the dumps we ingest.
    perl -i -pe 's/^(\s+"[^"]+"\s+)double(\s+)(?!precision)/$1double precision$2/g' "${out}"

    # Strip MySQL stored procedures and functions.
    #
    # The MySQL dumps wrap each procedure/function in a
    #   DROP PROCEDURE IF EXISTS `x`;     (or DROP FUNCTION)
    #   DELIMITER ;;
    #   CREATE DEFINER=... PROCEDURE/FUNCTION `x`(...) ... END;;
    #   DELIMITER ;
    # block. MySQL-flavoured PL (DELIMITER, DEFINER, CASE/WHEN/IF-THEN-END IF,
    # INT(N) parameter types) does not parse in Postgres, and the C++ server
    # no longer calls these — Phase N inlined every CALL into the libpqxx
    # path in server/src/{Account,Save,Server}Manager.cpp. The only
    # remaining `CALL net7_user.accLogin` is in WIN32-only
    # login-server/Net7SSL/AccountManager.cpp, which doesn't build on Linux.
    # Drop them rather than carry stale stubs that just spew errors at boot.
    perl -0777 -i -pe '
        s{(?:^--\s*-+\s*\n--\s*(?:Procedure|Function)\s+structure[^\n]*\n--\s*-+\s*\n)?DROP\s+(?:PROCEDURE|FUNCTION)\s+IF\s+EXISTS\s+"[^"]+";\s*\nDELIMITER\s+;;.*?DELIMITER\s+;\s*\n}{}gms;
    ' "${out}"

    # Strip trailing commas before the closing paren of CREATE TABLE.
    # Two passes:
    #   1. plain `,\s*\)` — original case
    #   2. `,\s*(-- (UNIQUE |FULLTEXT )?INDEX TODO:[^\n]*\n\s*)+\)` — comma
    #      before a run of `-- INDEX TODO` lines followed by `)`, which is
    #      what the KEY-rewrites can leave behind when KEY clauses are the
    #      last items inside the CREATE TABLE.
    perl -0777 -i -pe '
        s/,(\s*(?:--\s+(?:UNIQUE\s+|FULLTEXT\s+)?INDEX\s+TODO:[^\n]*\n\s*)+\))/\1/g;
        s/,(\s*(?:--\s+FK\s+TODO[^\n]*\n\s*)+\))/\1/g;
        s/,(\s*(?:--\s+(?:UNIQUE\s+|FULLTEXT\s+)?INDEX\s+TODO:[^\n]*\n\s*|--\s+FK\s+TODO[^\n]*\n\s*)+\))/\1/g;
        s/,(\s*\))/\1/g;
    ' "${out}"

    # Prepend a session-level setting so MySQL-style backslash escapes in
    # INSERT string literals ('foo\'s bar', '\n', '\\') still parse. This is
    # the unsightly-but-pragmatic fix for the seed data; Phase C will move
    # to a real loader.
    {
        echo "-- Generated by db/postgres/convert.sh — do not edit by hand."
        echo "SET standard_conforming_strings = off;"
        echo "SET escape_string_warning = off;"
        echo "SET client_min_messages = warning;"
        echo ""
        cat "${out}"
    } > "${out}.tmp" && mv "${out}.tmp" "${out}"

    local in_lines out_lines
    in_lines=$(wc -l < "${in}")
    out_lines=$(wc -l < "${out}")
    local table_count
    table_count=$(grep -c -E "^CREATE TABLE " "${out}" || true)
    echo "convert.sh: ${in} (${in_lines} lines) -> ${out} (${out_lines} lines, ${table_count} CREATE TABLE)"
}

echo "convert.sh: starting MySQL -> Postgres conversion"
convert "${SRC_DIR}/net7.sql"      "${DST_DIR}/schema.sql"

if [[ -f "${SRC_DIR}/net7_user.sql" ]]; then
    convert "${SRC_DIR}/net7_user.sql" "${DST_DIR}/seed.sql"
fi

echo "convert.sh: done. See ${DST_DIR}/README.md for known residual issues."
