-- external_status_events.sql -- server -> external-consumer event outbox (net7_user).
--
-- Phase AM. The game server publishes live status events (player login / logout
-- with the current online count, level-up, server broadcast, "server started")
-- for an out-of-process consumer to relay to a chat channel or dashboard. The
-- first consumer is a Discord webhook sidecar (status-notifier/), but nothing
-- here is Discord-specific -- the server only writes a generic event row.
--
-- The server does NOT contact the external service directly: pulling an
-- outbound HTTP client into the security-sensitive game process would widen its
-- attack surface for a convenience feature, which CLAUDE.md forbids. Instead the
-- server INSERTs a fully-rendered message line into this table and fires
-- `NOTIFY external_status_event` (both on the net7_user connection it already
-- holds via SaveManager); the sidecar LISTENs, drains the unsent rows, and
-- delivers each one.
--
-- Durable on purpose: a row sits here with sent_at = NULL until the sidecar
-- confirms delivery, so events survive a sidecar restart and nothing is
-- silently dropped. The sidecar catches up on its own startup by scanning
-- sent_at IS NULL before it settles into LISTEN.
--
-- Applied UNCONDITIONALLY by the schema-init service (CREATE TABLE IF NOT
-- EXISTS is idempotent), so it lands on pre-existing volumes too -- it is NOT
-- gated behind the accounts probe.
--
--   kind        one of 'login' | 'logout' | 'levelup' | 'broadcast' |
--               'server_start'. The sidecar may route by kind later; today it
--               just delivers content verbatim.
--   content     the final UTF-8 message line, rendered server-side (it has the
--               name / levels / class / online count; the sidecar stays dumb).
--   created_at  when the server enqueued the event.
--   sent_at     NULL until the sidecar confirms delivery for this row.

CREATE TABLE IF NOT EXISTS external_status_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        TEXT        NOT NULL,
    content     TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at     TIMESTAMPTZ
);

-- The sidecar's hot path is "give me every row not yet delivered, oldest
-- first". A partial index on the unsent rows keeps that scan cheap even as the
-- delivered backlog grows between retention sweeps.
CREATE INDEX IF NOT EXISTS external_status_events_unsent
    ON external_status_events (id) WHERE sent_at IS NULL;
