-- gate_events.sql -- per-transition sector-movement log (net7_user).
--
-- Phase AQ. Every time a player crosses between sectors -- gating through a
-- stargate, undocking from a station into its parent sector, or docking into a
-- station -- the game server appends one row here recording where they came
-- from, where they went, and when. It is the data source for the Freya Online
-- galaxy map's "traffic" animation: the website groups the last few minutes of
-- rows by ORDERED (from_sector, to_sector) pair and draws one travelling light
-- per event along that directed lane (see freya/online/server/store_gateflow.go).
--
-- This is a pure analytics side-write, NOT a wire-protocol change: the server
-- still emits the identical ServerHandoff packet to the client. The row is
-- enqueued on the SaveManager queue (like external_status_events) and written on
-- the SaveManager thread over the net7_user connection it already holds, so the
-- gameplay thread never blocks on this DB write and a failure here can never
-- stall a sector transition.
--
-- Direction matters: a hop A->B and a hop B->A are different ordered pairs and
-- animate in opposite directions, so we store from/to separately (no min/max
-- canonicalisation like the undirected gate-edge graph does).
--
-- Retention: the server prunes rows older than an hour on the SAME write that
-- inserts a new transition (SaveManager::HandleGateEvent), so this table stays
-- tiny without a separate sweeper. The website only reads the trailing 5-minute
-- window and never deletes. No long-lived history is kept here on purpose.
--
-- Applied UNCONDITIONALLY by schema-init (CREATE TABLE IF NOT EXISTS is
-- idempotent), so it lands on pre-existing volumes too.
--
--   avatar_id    the moving character (avatar_info.avatar_id). Not joined by the
--                website read, but kept so a row is attributable and a future
--                per-player trail is possible without a schema change.
--   from_sector  sector_id the player left.
--   to_sector    sector_id the player arrived in.
--   created_at   when the server recorded the transition.

CREATE TABLE IF NOT EXISTS gate_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avatar_id   INTEGER     NOT NULL,
    from_sector INTEGER     NOT NULL,
    to_sector   INTEGER     NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Both access patterns are bounded by created_at:
--   read:  WHERE created_at > now() - 5min  GROUP BY from_sector, to_sector
--   prune: DELETE WHERE created_at < now() - 1 hour  (server, on each insert)
-- A composite index led by created_at backs the range scan for both. Carrying
-- from_sector + to_sector in the index makes the read an index-only scan -- the
-- grouped columns come straight from the index, no heap fetch -- so the whole
-- aggregate is served from the index over just the trailing-window slice.
CREATE INDEX IF NOT EXISTS gate_events_window
    ON gate_events (created_at, from_sector, to_sector);
