-- seed_prospecting.sql -- GENERATED by tools/prospecting-import.
-- Applies prospecting-driven data: base_ore_list (which resources spawn
-- in which sector) and the resource fields the prospecting data indicates
-- but the DB lacked. Regenerate with tools/prospecting-import; do not
-- hand-edit. Runs AFTER the base seeds and the capture import.

\ir prospecting/base_ore_list.sql
\ir prospecting/fields.sql
