-- seed_captures.sql -- GENERATED by .claude/skills/import-captures.
-- Imports accurate captured object data (resources, mobs, navs) that
-- takes priority over the current emulator data. Per-sector files do
-- the work; this wrapper includes them. Regenerate with the skill;
-- do not hand-edit. See the skill SKILL.md for the policy.

-- global purge of any prior synthetic rows (clean re-apply, see _purge.sql)
\ir capture_import/_purge.sql

-- synthetic mob_base clone templates (must load before the spawns)
\ir capture_import/_mob_templates.sql

\ir capture_import/1005_Mercury.sql
\ir capture_import/1010_Venus.sql
\ir capture_import/1020_High_Earth.sql
\ir capture_import/1025_Equatorial_Earth.sql
\ir capture_import/1030_Mars_Beta.sql
\ir capture_import/1036_Mars_Alpha.sql
\ir capture_import/1040_Ganymede.sql
\ir capture_import/1052_Io.sql
\ir capture_import/1055_Europa.sql
\ir capture_import/1060_Earth.sql
\ir capture_import/1065_Mars.sql
\ir capture_import/1070_Jupiter.sql
\ir capture_import/1072_Uranus.sql
\ir capture_import/1073_Neptune.sql
\ir capture_import/1074_Pluto_and_Charon.sql
\ir capture_import/1075_Akerons_Gate.sql
\ir capture_import/1076_Asteroid_Belt_Alpha.sql
\ir capture_import/1077_Asteroid_Belt_Beta.sql
\ir capture_import/1078_Ceres_Thule_.sql
\ir capture_import/1115_Aganju.sql
\ir capture_import/1310_Altair_III.sql
\ir capture_import/1425_Zweihander.sql
\ir capture_import/1505_Antares_Frontier.sql
\ir capture_import/1705_Valkyrie_Twins.sql
\ir capture_import/1715_Varens_Girdle.sql
\ir capture_import/1720_Odins_Belt.sql
\ir capture_import/1725_Muspelheim.sql
\ir capture_import/1730_Fenris.sql
\ir capture_import/1735_Odin_Rex.sql
\ir capture_import/1740_Jotunheim.sql
\ir capture_import/1745_Ragnarok.sql
\ir capture_import/1750_Freya.sql
\ir capture_import/1910_Kailaasa.sql
\ir capture_import/1915_Kitara_s_Veil.sql
\ir capture_import/1920_Yokan.sql
\ir capture_import/1925_Dahin.sql
\ir capture_import/1935_Vishao_s_Cove.sql
\ir capture_import/2005_Ishuan.sql
\ir capture_import/2010_Menorb.sql
\ir capture_import/2210_Endriago.sql
\ir capture_import/2215_Lagarto.sql
\ir capture_import/3515_Primus.sql
\ir capture_import/3530_Tarsis.sql
\ir capture_import/3605_Blackbeards_Wake.sql
\ir capture_import/4015_New_Edinburgh.sql
\ir capture_import/4025_Inverness.sql
\ir capture_import/4030_Arduinne.sql
\ir capture_import/4115_Xipe_Totec.sql
\ir capture_import/4120_Swooping_Eagle.sql
\ir capture_import/4505_Glorys_Orbit.sql
\ir capture_import/4510_Slayton.sql
\ir capture_import/4515_Glenn.sql
\ir capture_import/4520_Carpenter.sql
\ir capture_import/4525_Shepard.sql
\ir capture_import/4530_Grissom.sql
