-- seed_captures.sql -- GENERATED by .claude/skills/import-captures.
-- Imports accurate captured object data (resources, mobs, navs) that
-- takes priority over the current emulator data. Per-sector files do
-- the work; this wrapper includes them. Regenerate with the skill;
-- do not hand-edit. See the skill SKILL.md for the policy.

-- global purge of any prior synthetic rows (clean re-apply, see _purge.sql)
\ir capture_import/_purge.sql

-- synthetic mob_base clone templates (must load before the spawns)
\ir capture_import/_mob_templates.sql

\ir capture_import/1005_Mercury.sql
\ir capture_import/1010_Venus.sql
\ir capture_import/1020_High_Earth.sql
\ir capture_import/1040_Ganymede.sql
\ir capture_import/1070_Jupiter.sql
\ir capture_import/1071_Saturn.sql
\ir capture_import/1072_Uranus.sql
\ir capture_import/1074_Pluto_and_Charon.sql
\ir capture_import/1075_Akerons_Gate.sql
\ir capture_import/1076_Asteroid_Belt_Alpha.sql
\ir capture_import/1750_Freya.sql
\ir capture_import/1910_Kailaasa.sql
\ir capture_import/1920_Yokan.sql
\ir capture_import/1925_Dahin.sql
\ir capture_import/2005_Ishuan.sql
\ir capture_import/2010_Menorb.sql
\ir capture_import/4015_New_Edinburgh.sql
\ir capture_import/4025_Inverness.sql
\ir capture_import/4030_Arduinne.sql
\ir capture_import/4120_Swooping_Eagle.sql
\ir capture_import/4515_Glenn.sql
\ir capture_import/4520_Carpenter.sql
