-- sync_sequences.sql -- advance every IDENTITY sequence in net7 to its
-- column MAX so the next auto-allocated id is MAX+1.
--
-- Why this exists: schema.sql and the Phase Y seeds bulk-load rows with
-- EXPLICIT primary-key values (a GENERATED BY DEFAULT AS IDENTITY column
-- accepts a supplied value and does NOT advance its backing sequence when
-- it does). After a fresh apply, every identity sequence therefore sits at
-- last_value=1 while the data already occupies ids up to ~200528. Any
-- INSERT that omits the id and lets the identity allocate (the editor
-- suite's "new row" path, via INSERT ... RETURNING) would generate 1, 2,
-- 3, ... and collide with existing rows -- effectively never succeeding
-- until the sequence organically climbed past MAX.
--
-- This is the canonical post-bulk-load fixup. It is generic (covers every
-- public identity column, not just the ones the editors touch), idempotent,
-- and cheap, so schema-init runs it unconditionally on every boot.
DO $$
DECLARE
    r       RECORD;
    seqname text;
    maxv    bigint;
BEGIN
    FOR r IN
        SELECT table_schema, table_name, column_name
        FROM information_schema.columns
        WHERE is_identity = 'YES'
          AND table_schema = 'public'
    LOOP
        seqname := pg_get_serial_sequence(
            format('%I.%I', r.table_schema, r.table_name), r.column_name);
        IF seqname IS NULL THEN
            CONTINUE;
        END IF;
        EXECUTE format('SELECT COALESCE(MAX(%I), 0) FROM %I.%I',
                       r.column_name, r.table_schema, r.table_name)
            INTO maxv;
        -- is_called=true so the next nextval() returns maxv+1 (not maxv).
        -- GREATEST(maxv,1) keeps an empty table's sequence at a sane 1.
        PERFORM setval(seqname, GREATEST(maxv, 1), true);
    END LOOP;
END $$;
