using System;
using System.Data;
using CommonTools.Database;

namespace N7.Sql
{
    // Parameterised port of tools/sector-editor/Sql/SectorsSql.cs. The original
    // built UPDATE/INSERT strings with 30+ "'" + r["col"] + "'" concatenations
    // per call — every one a SQL-injection sink. Here every column rides on a
    // @param placeholder so Npgsql binds it.
    public class SectorsSql
    {
        private DataTable sectors;

        public SectorsSql()
        {
            sectors = Database.executeQuery(Database.DatabaseName.net7,
                "SELECT * FROM sectors order by system_id, name");
        }

        public DataTable getSectorTable() => sectors;

        public DataRow[] findRowsByName(String name)
            => sectors.WhereTextEquals("name", name);

        public DataRow[] getRowsBySystemID(String systemID)
            => sectors.WhereIntEquals("system_id", long.Parse(systemID));

        public DataTable queryBySystemID(String systemID)
        {
            return Database.executeQuery(Database.DatabaseName.net7,
                "SELECT * FROM sectors where system_id=@sid order by name",
                new String[] { "sid" },
                new String[] { systemID });
        }

        public int getIDFromName(String name)
        {
            DataRow[] foundRows = sectors.WhereTextEquals("name", name);
            return int.Parse(foundRows[0]["sector_id"].ToString());
        }

        private static readonly String[] AllCols = new String[]
        {
            "name", "x_min", "x_max", "y_min", "y_max", "z_min", "z_max",
            "grid_x", "grid_y", "grid_z", "fog_near", "fog_far", "debris_mode",
            "light_backdrop", "fog_backdrop", "swap_backdrop",
            "backdrop_fog_near", "backdrop_fog_far", "max_tilt", "auto_level",
            "impulse_rate", "decay_velocity", "decay_spin", "backdrop_asset",
            "greetings", "notes", "system_id", "galaxy_x", "galaxy_y",
            "galaxy_z", "sector_type"
        };

        public void updateRow(DataRow r)
        {
            String[] paramNames = new String[AllCols.Length + 1];
            String[] paramValues = new String[AllCols.Length + 1];
            String setClause = "";
            for (int i = 0; i < AllCols.Length; i++)
            {
                paramNames[i] = AllCols[i];
                paramValues[i] = r[AllCols[i]].ToString();
                if (setClause.Length > 0) setClause += ", ";
                setClause += AllCols[i] + "=@" + AllCols[i];
            }
            paramNames[AllCols.Length] = "sector_id";
            paramValues[AllCols.Length] = r["sector_id"].ToString();

            String query = "UPDATE sectors SET " + setClause + " WHERE sector_id=@sector_id";
            Database.executeCommand(Database.DatabaseName.net7, query, paramNames, paramValues);
        }

        public void newRow(DataRow r)
        {
            // sector_id is GENERATED BY DEFAULT AS IDENTITY -- do NOT supply it
            // (the DataRow's value is just the DataTable's auto-increment seed,
            // not a real id). Let Postgres allocate it and hand it back via
            // RETURNING, then write the real id onto the row.
            String[] paramNames = new String[AllCols.Length];
            String[] paramValues = new String[AllCols.Length];
            String colList = "";
            String valList = "";
            for (int i = 0; i < AllCols.Length; i++)
            {
                paramNames[i] = AllCols[i];
                paramValues[i] = r[AllCols[i]].ToString();
                if (colList.Length > 0) { colList += ", "; valList += ", "; }
                colList += AllCols[i];
                valList += "@" + AllCols[i];
            }

            String query = "INSERT INTO sectors (" + colList + ") VALUES (" + valList
                         + ") RETURNING \"sector_id\" AS id";
            DataTable res = Database.executeQuery(Database.DatabaseName.net7, query, paramNames, paramValues);
            r["sector_id"] = Convert.ToInt64(res.Rows[0]["id"]);
        }
    }
}
