using System;
using System.Data;
using CommonTools.Database;

namespace N7.Sql
{
    // Parameterised port of tools/sector-editor/Sql/SystemsSql.cs.
    public class SystemsSql
    {
        private DataTable systems;

        public SystemsSql()
        {
            systems = Database.executeQuery(Database.DatabaseName.net7, "Select * from systems");
        }

        public DataTable getSystemTable() => systems;

        public DataRow[] findRowsByName(String name)
            => systems.WhereTextEquals("name", name);

        public String findRowNameByID(int id)
        {
            DataRow[] foundRows = systems.WhereIntEquals("system_id", id);
            return foundRows[0]["name"].ToString();
        }

        public int getIDFromName(String name)
        {
            DataRow[] foundRows = systems.WhereTextEquals("name", name);
            return int.Parse(foundRows[0]["system_id"].ToString());
        }

        private static readonly String[] UpdateCols = new String[]
        {
            "name", "galaxy_x", "galaxy_y", "galaxy_z",
            "color_r", "color_g", "color_b", "notes"
        };

        public void updateRow(DataRow r)
        {
            String[] paramNames = new String[UpdateCols.Length + 1];
            String[] paramValues = new String[UpdateCols.Length + 1];
            String setClause = "";
            for (int i = 0; i < UpdateCols.Length; i++)
            {
                paramNames[i] = UpdateCols[i];
                paramValues[i] = r[UpdateCols[i]].ToString();
                if (setClause.Length > 0) setClause += ", ";
                setClause += UpdateCols[i] + "=@" + UpdateCols[i];
            }
            paramNames[UpdateCols.Length] = "system_id";
            paramValues[UpdateCols.Length] = r["system_id"].ToString();

            String query = "UPDATE systems SET " + setClause + " WHERE system_id=@system_id";
            Database.executeCommand(Database.DatabaseName.net7, query, paramNames, paramValues);
        }

        public void newRow(DataRow nr)
        {
            String[] paramNames = new String[UpdateCols.Length];
            String[] paramValues = new String[UpdateCols.Length];
            String colList = "";
            String valList = "";
            for (int i = 0; i < UpdateCols.Length; i++)
            {
                paramNames[i] = UpdateCols[i];
                paramValues[i] = nr[UpdateCols[i]].ToString();
                if (colList.Length > 0) { colList += ", "; valList += ", "; }
                colList += UpdateCols[i];
                valList += "@" + UpdateCols[i];
            }

            // system_id is GENERATED BY DEFAULT AS IDENTITY; RETURNING hands back
            // the freshly-minted id directly (no LAST_INSERT_ID() round trip).
            String query = "INSERT INTO systems (" + colList + ") VALUES (" + valList
                         + ") RETURNING \"system_id\" AS id";
            DataTable res = Database.executeQuery(Database.DatabaseName.net7, query, paramNames, paramValues);

            nr["system_id"] = Convert.ToInt64(res.Rows[0]["id"]);
        }
    }
}
